"""Parallel ru/en/es copy for the PEV1 profession flow."""

PROFESSION_KEYS = (
    'herbalism','woodcutting','mining','fishing','hunting',
    'heavy_armor','medium_armor','light_armor','blacksmith','arcane_engineer','alchemy','cooking',
)

NAMES = {
 'ru': {'herbalism':'Травничество','woodcutting':'Лесозаготовка','mining':'Горное дело','fishing':'Рыболовство','hunting':'Охота','heavy_armor':'Изготовление тяжёлой брони','medium_armor':'Изготовление средней брони','light_armor':'Изготовление лёгкой брони','blacksmith':'Кузнечное дело','arcane_engineer':'Магическая инженерия','alchemy':'Алхимия','cooking':'Кулинария'},
 'en': {'herbalism':'Herbalism','woodcutting':'Woodcutting','mining':'Mining','fishing':'Fishing','hunting':'Hunting','heavy_armor':'Heavy armor crafting','medium_armor':'Medium armor crafting','light_armor':'Light armor crafting','blacksmith':'Blacksmithing','arcane_engineer':'Arcane engineering','alchemy':'Alchemy','cooking':'Cooking'},
 'es': {'herbalism':'Herboristería','woodcutting':'Tala','mining':'Minería','fishing':'Pesca','hunting':'Caza','heavy_armor':'Fabricación de armadura pesada','medium_armor':'Fabricación de armadura media','light_armor':'Fabricación de armadura ligera','blacksmith':'Herrería','arcane_engineer':'Ingeniería arcana','alchemy':'Alquimia','cooking':'Cocina'},
}

STRINGS = {
 'ru': {'title':'🛠 <b>Профессии</b>','gathering':'Собирательные','crafting':'Ремесленные','level':'Уровень {level} · опыт {exp}/{needed}','cap':'Уровень 20 · максимум','known':'Известные','learnable':'Доступно изучить','locked':'Закрытые','recipe_level':'Требуется уровень {level}','learning':'Изучение: {gold} золота · навсегда','ingredients':'Материалы','owned':'есть {owned}/{required}','craftable':'Можно создать сейчас','not_craftable':'Сейчас создать нельзя','learn':'📖 Изучить','craft':'🔨 Создать','learned':'Рецепт изучен.','crafted':'Предмет создан.','already_known':'Рецепт уже известен.','missing_materials':'Не хватает материалов.','profession_level_too_low':'Недостаточный уровень профессии.','recipe_not_found':'Рецепт недоступен.','wrong_location':'Нужна гильдия ремесленников.','insufficient_gold':'Недостаточно золота.','stale_action':'Действие устарело.','sources':'Источники','chance':'{place}: {chance}%','consumers':'Используется в рецептах','sale':'Продажа: {gold} золота','back':'⬅️ Назад','receipts':'🧾 История действий','page':'Страница {page}/{pages}','band_1':'Базовый образец','band_6':'Региональный образец','band_12':'Продвинутый образец','band_18':'Поздний альфа-проект'},
 'en': {'title':'🛠 <b>Professions</b>','gathering':'Gathering','crafting':'Crafting','level':'Level {level} · XP {exp}/{needed}','cap':'Level 20 · maximum','known':'Known','learnable':'Learnable','locked':'Locked','recipe_level':'Requires level {level}','learning':'Learn for {gold} gold · permanent','ingredients':'Ingredients','owned':'owned {owned}/{required}','craftable':'Craftable now','not_craftable':'Not craftable now','learn':'📖 Learn','craft':'🔨 Craft','learned':'Recipe learned.','crafted':'Item crafted.','already_known':'Recipe already known.','missing_materials':'Missing materials.','profession_level_too_low':'Profession level is too low.','recipe_not_found':'Recipe is unavailable.','wrong_location':'A craftsmen’s guild is required.','insufficient_gold':'Not enough gold.','stale_action':'This action is stale.','sources':'Sources','chance':'{place}: {chance}%','consumers':'Used by recipes','sale':'Sale value: {gold} gold','back':'⬅️ Back','receipts':'🧾 Action history','page':'Page {page}/{pages}','band_1':'Basic pattern','band_6':'Regional pattern','band_12':'Advanced pattern','band_18':'Late-alpha project'},
 'es': {'title':'🛠 <b>Profesiones</b>','gathering':'Recolección','crafting':'Artesanía','level':'Nivel {level} · EXP {exp}/{needed}','cap':'Nivel 20 · máximo','known':'Conocidas','learnable':'Aprendibles','locked':'Bloqueadas','recipe_level':'Requiere nivel {level}','learning':'Aprender por {gold} de oro · permanente','ingredients':'Ingredientes','owned':'tienes {owned}/{required}','craftable':'Se puede fabricar ahora','not_craftable':'No se puede fabricar ahora','learn':'📖 Aprender','craft':'🔨 Fabricar','learned':'Receta aprendida.','crafted':'Objeto fabricado.','already_known':'La receta ya es conocida.','missing_materials':'Faltan materiales.','profession_level_too_low':'Nivel de profesión insuficiente.','recipe_not_found':'La receta no está disponible.','wrong_location':'Se requiere un gremio de artesanos.','insufficient_gold':'No hay suficiente oro.','stale_action':'La acción ha caducado.','sources':'Fuentes','chance':'{place}: {chance}%','consumers':'Usado en recetas','sale':'Venta: {gold} de oro','back':'⬅️ Volver','receipts':'🧾 Historial de acciones','page':'Página {page}/{pages}','band_1':'Patrón básico','band_6':'Patrón regional','band_12':'Patrón avanzado','band_18':'Proyecto avanzado de alfa'},
}

for language in STRINGS:
    STRINGS[language]['names'] = NAMES[language]

STRINGS['ru'].update({'receipt_detail':'🧾 <b>Результат действия</b>','gold_result':'Золото: {delta:+} · осталось {after}','receipt_consumed':'Списано','receipt_granted':'Получено','none':'—','harvested':'Ресурс получен.','empty':'Ничего не найдено.','denied':'Ресурс пока закрыт.','rested':'Отдых завершён.','sold':'Предмет продан.','used':'Предмет использован.','gifted':'Подарок отправлен.','exchanged':'Обмен завершён.','in_battle':'Действие недоступно в бою.'})
STRINGS['en'].update({'receipt_detail':'🧾 <b>Action result</b>','gold_result':'Gold: {delta:+} · {after} remaining','receipt_consumed':'Consumed','receipt_granted':'Granted','none':'—','harvested':'Resource collected.','empty':'Nothing was found.','denied':'That resource is still locked.','rested':'Rest complete.','sold':'Item sold.','used':'Item used.','gifted':'Gift sent.','exchanged':'Exchange complete.','in_battle':'This action is unavailable in battle.'})
STRINGS['es'].update({'receipt_detail':'🧾 <b>Resultado de la acción</b>','gold_result':'Oro: {delta:+} · quedan {after}','receipt_consumed':'Consumido','receipt_granted':'Obtenido','none':'—','harvested':'Recurso obtenido.','empty':'No se encontró nada.','denied':'Ese recurso sigue bloqueado.','rested':'Descanso completado.','sold':'Objeto vendido.','used':'Objeto usado.','gifted':'Regalo enviado.','exchanged':'Intercambio completado.','in_battle':'Esta acción no está disponible en combate.'})

_DESCRIPTION = {
    'ru': 'Развивайте профессию до 20 уровня, открывая новые источники и рецепты.',
    'en': 'Advance this profession to level 20 to unlock new sources and recipes.',
    'es': 'Mejora esta profesión hasta el nivel 20 para desbloquear fuentes y recetas.',
}
for language in STRINGS:
    STRINGS[language]['descriptions'] = {key: _DESCRIPTION[language] for key in PROFESSION_KEYS}
