"""Localización española completa de RAV1-1."""

from locales.rav1_en import STRINGS as _EN


STRINGS = {
 "nav":{"home":"Oportunidades regionales","nearby":"Cerca","leads":"Pistas","pursuits":"Objetivos","regions":"Regiones","resolved":"Resuelto","work":"Trabajo local","back":"Volver","previous":"Anterior","next":"Siguiente","map":"Mapa","inventory":"Inventario","history":"Historial","professions":"Profesiones","equipment":"Equipo y configuración","build":"Configuración","opportunities":"Oportunidades"},
 "status":{"available":"Disponible","active":"Activo","resolved":"Resuelto","found":"Hallado","unknown":"Desconocido","local":"Aquí","remote":"En otro lugar","pinned":"Fijado","one_time":"Una vez","repeatable":"Por lote","optional":"Opcional","busy":"Ocupado","respawning":"Reapareciendo"},
 "actions":{"start":"Aceptar proyecto local","inspect":"Inspeccionar","deliver":"Entregar","respond":"Responder","choose":"Elegir","confirm":"Confirmar","cancel":"Volver / Cancelar","claim":"Recoger","pin":"Fijar","unpin":"Quitar","refresh":"Actualizar","open":"Abrir","source":"Fuente","recipe":"Receta","rest":"Descansar"},
 "errors":{"no_player":"Crea primero un personaje.","stale_action":"La acción ha caducado. Abre el registro actual e inténtalo de nuevo.","wrong_location":"Debes estar en el lugar indicado.","in_battle":"Termina primero el encuentro actual.","insufficient_goods":"No tienes el lote completo requerido.","pins_full":"Quita primero un objetivo fijado.","already_resolved":"Este registro finito ya está resuelto.","project_not_active":"Ese proyecto no está activo.","incompatible_step":"El proyecto cambió. Abre sus objetivos actuales.","not_discovered":"Inspecciona primero el punto indicado.","unknown_content":"Esa oportunidad no está disponible.","malformed_action":"El botón no es válido.","incompatible_version":"El registro no es compatible con el catálogo actual.","temporary_atomic_failure":"No se gastó nada; inténtalo de nuevo.","busy_target":"Los enemigos compartidos están ocupados; actualiza tras la lucha o elige otra actividad.","respawning_target":"El objetivo compartido está reapareciendo."},
 "rewards":{"line":"Recompensa: {xp} EXP · {gold} de oro · {items}","none":"sin objetos","equal":"Ambas elecciones dan la misma recompensa.","standing_xp":"Sin EXP de personaje, maestría, profesión ni puntos de cazador.","hidden":"El contenido de la recompensa permanece oculto hasta completar las referencias."},
 "readiness":{"risk":"Riesgo: {risk}","not_gate":"La información de riesgo no bloquea por nivel.","profession":"La producción opcional requiere {profession} de nivel {level}.","multi":"Número de enemigos: {count}.","enemy":"{enemy} · nivel {level} · {traits}","standard":"ataques normales","armored":"armadura","evasive":"evasión alta","heavy":"tercer ataque pesado","venom":"veneno al tercer impacto","drain":"drenaje al tercer impacto","ferry":"Este encuentro exacto es necesario para el proyecto opcional de la tripulación."},
 "people":{"mara":"Mara","iven":"Iven","sera":"Sera","oren":"Oren","lida":"Lida","storekeeper":"almacenista del gremio de Karn"},
 "landmarks":{"ww_greyfang_tracks":"Huellas de pata hendida","ww_root_marks":"Marcas de leñador en las raíces","fs_survey_stone":"Piedra topográfica","ar_temple_names":"Monumento retallado","ar_garden_ledger":"Cuenta del jardinero","ar_storehouse_seal":"Sello doméstico","mv_ford_marks":"Marcas del embarcadero","mv_fungal_observation":"Nota del pescador","ss_camp_marks":"Marcas de orientación del campamento","ss_pillar_shadow":"Sombra del pilar","fs_sled_damage":"Daño del trineo","mv_channel_rope":"Cuerda del canal"},
 "regions":{
  "region_westwild":{"title":"Tierras Occidentales","summary":"Trabajadores y cazadores cerca de Elmor: herramientas, huellas de lobos, provisiones y cacerías normales.","risk":"Ruta temprana; las manadas profundas y élites son opcionales. Las oportunidades son independientes."},
  "region_frostspine":{"title":"Cresta Helada","summary":"Reparaciones, suministros de forja, lobos blancos y una pareja acorazada opcional en el paso.","risk":"El trineo admite materiales básicos o un solo rival. Las oportunidades son independientes."},
  "region_ashen_ruins":{"title":"Ruinas Cinéreas","summary":"Compara un monumento y una cuenta de jardín, o examina un almacén inquieto, en cualquier orden.","risk":"Los no muertos superan a las criaturas iniciales; inspeccionar no exige luchar. Las oportunidades son independientes."},
  "region_sunscar":{"title":"Cicatriz Solar","summary":"Lee las referencias de un campamento, caza escorpiones o busca un elemental esquivo.","risk":"Los pilares y elementales están más lejos; el objetivo con nombre es opcional. Las oportunidades son independientes."},
  "region_mireveil":{"title":"Velo Pantanoso","summary":"Sigue a una tripulación, ayuda a una sanadora, practica alquimia o lleva comida al embarcadero.","risk":"La ruta del ferry incluye dos depredadores juntos; la práctica médica es opcional. Las oportunidades son independientes."},
 },
 "content":{},
 "facts":{"no_reward":"La inspección registra un hallazgo, pero no da EXP, oro ni objetos.","already":"Ya registraste este hallazgo.","new":"Hallazgo registrado."},
 "choices":{"preview":"Revisa la consecuencia antes de confirmarla.","selected":"Elegido: {choice}","permanent":"Esta elección es permanente para este personaje. Las recompensas son iguales. Las rutas y demás actividades seguirán abiertas.","shared_credit":"Reconocer a ambos trabajadores","leave_unattributed":"Conservar la prueba sin atribución","archive_seal":"Archivar el sello doméstico","leave_seal":"Dejar el sello con los restos","save_supplies":"Salvar los suministros","save_log":"Salvar el cuaderno de ruta","shared_credit_after":"Ambos nombres quedan junto al trabajo del jardín.","leave_unattributed_after":"La prueba se conserva y el mérito queda abierto.","archive_seal_after":"El sello doméstico queda catalogado aquí.","leave_seal_after":"Su lugar en el almacén queda registrado y respetado.","save_supplies_after":"Oren agradece las provisiones recuperadas.","save_log_after":"Oren agradece que conservaras el registro de la tripulación."},
 "work":{"title":"Trabajo local","owned":"Tienes: {owned}/{required}","item_owned":"{item}: tienes {owned}/{required}","exact_consumption":"Confirmar consume exactamente el lote completo indicado.","shortage":"Falta: {missing}","remote":"Viaja a {place} para entregar.","fresh_batch":"Cada entrega consume un lote completo nuevo."},
 "encounters":{"greyfang":{"title":"Colmillo Gris","summary":"Lobo de bosque especial de perfil normal en las colinas occidentales."},"salt_ridge_drifter":{"title":"Errante de la cresta salina","summary":"Elemental de aire élite opcional en los pilares, sin recompensa separada."},"rav1_frostspine_n6_pass":{"title":"Piedra en el paso","summary":"Dos fuentes normales: gólem pétreo montano delante y escarabajo pétreo en cuerpo a cuerpo."},"rav1_mireveil_n6_crosscurrent":{"title":"Depredadores de la contracorriente","summary":"Dos fuentes normales: sanguijuela gigante y serpiente de agua. El ferry exige este encuentro exacto."},"respawn_in":"Disponible de nuevo en unos {seconds} segundos."},
 "services":{"inn":"Posada de pago: 12 de oro.","board":"Tablón de contratos de caza","inn_result":"Descanso completado por 12 de oro.","no_discount":"El trabajo regional no ofrece curación gratis ni descuentos."},
 "replay":{"saved":"Se recuperó el resultado confirmado sin repetir costes ni recompensas.","current_language":"Los resultados guardados se muestran en tu idioma actual.","operation":"Operación confirmada: {operation}","consumed":"Consumido: {item} ×{quantity}","granted":"Obtenido: {item} ×{quantity}","xp":"EXP obtenida: {amount}","gold":"Oro obtenido: {amount}; saldo {after}."},
 "help":{"nonlinear":"No hay misión principal ni orden regional obligatorio.","pins":"Los fijados solo afectan a la presentación. Quitarlos no cancela progreso.","travel":"Los enlaces del diario respetan el mapa y las reglas normales de viaje.","empty_nearby":"No hay acción local aquí. Consulta el mapa, las regiones o tus objetivos.","empty_pursuits":"Elige trabajo local, explora o mejora equipo y profesiones.","empty_resolved":"Tus registros locales aparecerán aquí."},
 "progress":{"step":"Paso {current}/{total}","objective":"{label}: {current}/{required}","destinations":"Destino actual: {places}","repair_method":"Método de reparación registrado: {method}","projects":"{active} proyectos locales activos","discoveries":"{found} hallazgos registrados","no_global":"Las regiones son pares; no existe un porcentaje global de finalización."},
}


def _p(title, summary, start, steps, objectives, complete):
 return {"title":title,"summary":summary,"start":start,"step":steps,"objective":objectives,"complete":complete}


STRINGS["content"] = {
 "ww_tool_roll":_p("La bolsa de herramientas perdida","Recupera la bolsa de Mara de un lobo y vuelve a informar.","Un lobo arrastró la bolsa con olor a carne hacia las colinas.",{"recover":"Recuperar la bolsa","return":"Volver con Mara"},{"wolf":"Derrota un lobo de bosque en las colinas occidentales tras aceptar.","report":"Informa a Mara en Elmor."},"Mara recupera sus herramientas."),
 "fs_jammed_sled":_p("El trineo atascado","Inspecciona el patín, repáralo con materiales o una abrazadera recuperada e informa.","El trineo de Iven está parado junto a la mina vieja.",{"damage":"Inspeccionar el daño","repair":"Reparar el patín","report":"Informar a Iven"},{"inspect":"Inspecciona el patín roto.","materials":"Entrega 2 maderas comunes y 1 mineral de hierro.","clear_lizard":"Derrota un lagarto de roca normal en el sendero inferior de la montaña.","receipt":"Vuelve con Iven en Karn."},"El trineo vuelve a funcionar."),
 "ar_two_names":_p("Dos nombres en una piedra","Compara dos pruebas y decide cómo registra Sera una autoría incierta.","Sera pide pruebas, no una profecía.",{"evidence":"Comparar pruebas","record":"Registrar atribución"},{"temple":"Inspecciona el monumento retallado.","garden":"Inspecciona la cuenta del jardinero.","attribution":"Reconoce a ambos o deja la obra sin atribuir."},"Sera conserva tu registro local permanente."),
 "ar_unquiet_storehouse":_p("El almacén inquieto","Inspecciona el sello, vence a su guardián normal y decide su destino.","El almacén repite el sonido de una puerta al cerrarse.",{"seal":"Inspeccionar el sello","watch":"Vencer al guardián","disposition":"Registrar el destino"},{"mark":"Inspecciona el sello en el almacén.","guard":"Derrota un guardián esqueleto normal.","seal_fate":"Archiva el sello o déjalo con los restos."},"Sera registra el destino del sello doméstico."),
 "mv_ferry_crew":_p("La tripulación desaparecida","Sigue dos rastros, vence al encuentro exacto, salva una carga e informa.","Oren señala una cuerda de ferry abandonada.",{"trail":"Seguir el rastro","clear":"Despejar el canal","salvage":"Salvar una carga","return":"Volver con Oren"},{"ford":"Inspecciona las marcas del embarcadero.","channel":"Inspecciona la cuerda del canal.","channel_threat":"Vence a Depredadores de la contracorriente en el cruce del canal.","cargo":"Salva suministros o el cuaderno en el embarcadero río arriba.","report":"Informa a Oren en Velm."},"La tripulación está a salvo y Oren recibe el informe."),
 "ss_camp_bearings":_p("Las referencias del campamento","Alinea las marcas con la sombra del pilar y abre una vez el escondite.","El campamento abandonado conserva marcas fijas.",{"bearings":"Confirmar referencias","cache":"Abrir el hueco"},{"camp":"Inspecciona las marcas del campamento.","pillars":"Inspecciona la sombra del pilar.","open_cache":"Abre el escondite en el campamento."},"Recuperaste los suministros protegidos."),
 "mv_medic_practice":_p("Un lote nuevo para Lida","Tras aceptar, fabrica personalmente dos pociones de salud pequeñas con la receta inicial y entrégalas.","Práctica opcional de alquimia con la receta inicial de poción de salud pequeña.",{"practice":"Crear dos tónicos nuevos","hand_in":"Entregar el lote"},{"fresh_tonics":"Fabrica con éxito dos veces la receta inicial de poción de salud pequeña.","tonics":"Entrega 2 pociones de salud pequeñas a Lida."},"Lida acepta el lote nuevo."),
 "ww_greyfang_tracks":{"title":"Huellas de pata hendida","summary":"Un lobo con nombre regresa a estas colinas.","finding":"Una garra exterior hendida identifica al lobo que vuelve aquí. Colmillo Gris sigue siendo un objetivo compartido normal."},
 "ww_root_marks":{"title":"Marcas de leñador en las raíces","summary":"Las marcas señalan un hueco seco.","finding":"Las marcas revelan el escondite seco entre raíces."},
 "fs_survey_stone":{"title":"Piedra topográfica","summary":"Las cuadrillas separaron el paso del ramal minero.","finding":"La piedra distingue ambas rutas y menciona pino helado más arriba."},
 "ar_temple_names":{"title":"Monumento retallado","summary":"Dos nombres comparten una línea.","finding":"La piedra muestra una corrección antigua, no una profecía real."},
 "ar_garden_ledger":{"title":"Cuenta del jardinero","summary":"Dos trabajadores cuidaron el jardín en estaciones distintas.","finding":"La cuenta apoya un trabajo compartido sin probar autoría única."},
 "ar_storehouse_seal":{"title":"Sello doméstico","summary":"Un sello familiar común descansa bajo un eco inquieto.","finding":"Un guardián vigila el sello mientras la sala repite una puerta."},
 "mv_ford_marks":{"title":"Marcas del embarcadero","summary":"Raspaduras y cuerda cortada apuntan al canal.","finding":"Las señales indican que la tripulación fue río arriba."},
 "mv_fungal_observation":{"title":"Nota del pescador","summary":"Babosas y limo se acumulan en el agua fúngica.","finding":"La nota distingue la pesca normal de fuentes profundas."},
 "ss_camp_marks":{"title":"Marcas de orientación del campamento","summary":"Los cortes alinean el hueco con dos pilares.","finding":"Las marcas dan la primera mitad de la orientación fija."},
 "ss_pillar_shadow":{"title":"Sombra del pilar","summary":"Una línea fija confirma la orientación.","finding":"La sombra confirma el rumbo y menciona al Errante; no exige esperar una hora real."},
 "fs_sled_damage":{"title":"Daño del trineo","summary":"El patín está partido junto a la mina.","finding":"Puede repararse con materiales o una abrazadera junto a los lagartos del sendero inferior."},
 "mv_channel_rope":{"title":"Cuerda del canal","summary":"La cuerda está atada sobre el agua.","finding":"Hay supervivientes río arriba y depredadores en el cruce del canal."},
 "ww_woodcutter_provisions":{"title":"Provisiones para los leñadores","summary":"Prima única por 2 raciones de campo.","preview":"Entrega 2 raciones a Mara por 20 EXP y 18 de oro.","result":"Los leñadores reciben las provisiones."},
 "mv_medic_table":{"title":"La mesa de la sanadora","summary":"Petición única de 4 hierbas comunes.","preview":"Entrega 4 hierbas a Lida por 20 EXP y 18 de oro.","result":"Lida abastece la mesa médica."},
 "ww_root_cache":{"title":"El escondite seco entre raíces","summary":"Escondite único revelado por las marcas.","preview":"Recoge 1 poción pequeña y 1 fragmento de mejora.","result":"El escondite queda vacío."},
 "ww_ration_order":{"title":"Encargo habitual de los leñadores","summary":"Reventa local repetible de raciones cocinadas.","terms":"2 raciones de campo → 10 de oro por lote nuevo.","result":"Mara paga 10 de oro."},
 "fs_forge_supplies":{"title":"Suministros para la forja","summary":"Reventa local repetible de mineral y carbón.","terms":"2 minerales de hierro + 2 carbones → 20 de oro.","result":"El almacenista paga 20 de oro."},
 "mv_stew_order":{"title":"Comidas para el embarcadero","summary":"Entrega repetible de guiso del pantano.","terms":"2 guisos del pantano → 12 de oro.","result":"Oren paga 12 de oro."},
}

assert set(STRINGS) == set(_EN)
