# ============================================================
# items_data.py — все предметы игры
# ============================================================


from game.itemization import get_item_archetype_metadata
ITEMS = {

    # ── ОРУЖИЕ ──────────────────────────────────────────────

    'wooden_sword': {
        'item_id': 'wooden_sword', 'name': '🗡️ Деревянный меч',
        'description': 'Простой меч из дерева. Лучше чем ничего.',
        'item_type': 'weapon', 'weapon_type': 'melee', 'weapon_profile': 'sword_1h',
        'rarity': 'common',
        'damage_min': 5, 'damage_max': 8, 'defense': 0, 'weight': 3,
        'req_level': 1, 'req_strength': 0, 'req_agility': 0,
        'req_intuition': 0, 'req_wisdom': 0,
        'buy_price': 50, 'sell_price': 10,
        'skills_json': '[]', 'stat_bonus_json': '{}',
    },
    'iron_sword': {
        'item_id': 'iron_sword', 'name': '⚔️ Железный меч',
        'description': 'Надёжный железный меч.',
        'item_type': 'weapon', 'weapon_type': 'melee', 'weapon_profile': 'sword_1h',
        'rarity': 'common',
        'damage_min': 12, 'damage_max': 18, 'defense': 0, 'weight': 4,
        'req_level': 3, 'req_strength': 5, 'req_agility': 0,
        'req_intuition': 0, 'req_wisdom': 0,
        'buy_price': 200, 'sell_price': 50,
        'skills_json': '[]', 'stat_bonus_json': '{"strength": 2}',
    },
    'short_bow': {
        'item_id': 'short_bow', 'name': '🏹 Короткий лук',
        'description': 'Лёгкий лук для быстрой стрельбы.',
        'item_type': 'weapon', 'weapon_type': 'ranged', 'weapon_profile': 'bow',
        'rarity': 'common',
        'damage_min': 8, 'damage_max': 14, 'defense': 0, 'weight': 2,
        'req_level': 1, 'req_strength': 0, 'req_agility': 3,
        'req_intuition': 0, 'req_wisdom': 0,
        'buy_price': 80, 'sell_price': 20,
        'skills_json': '[]', 'stat_bonus_json': '{"agility": 1}',
    },
    'magic_staff': {
        'item_id': 'magic_staff', 'name': '🔮 Магический посох',
        'description': 'Посох начинающего мага.',
        'item_type': 'weapon', 'weapon_type': 'magic', 'weapon_profile': 'magic_staff',
        'rarity': 'uncommon',
        'damage_min': 80, 'damage_max': 100, 'defense': 0, 'weight': 3,
        'req_level': 3, 'req_strength': 0, 'req_agility': 0,
        'req_intuition': 5, 'req_wisdom': 0,
        'buy_price': 300, 'sell_price': 80,
        'skills_json': '[]', 'stat_bonus_json': '{"intuition": 2}',
    },
    'holy_staff': {
        'item_id': 'holy_staff', 'name': '✨ Святой посох',
        'description': 'Посох жреца. Наносит урон светом и лечит союзников.',
        'item_type': 'weapon', 'weapon_type': 'light', 'weapon_profile': 'holy_staff',
        'rarity': 'uncommon',
        'damage_min': 10, 'damage_max': 16, 'defense': 0, 'weight': 3,
        'req_level': 3, 'req_strength': 0, 'req_agility': 0,
        'req_intuition': 0, 'req_wisdom': 5,
        'buy_price': 300, 'sell_price': 80,
        'skills_json': '[]', 'stat_bonus_json': '{"wisdom": 2}',
    },
    'holy_rod': {
        'item_id': 'holy_rod', 'name': '🪄 Священный жезл',
        'description': 'Боевой жезл паладина. Сочетает святую защиту и карающий свет.',
        'item_type': 'weapon', 'weapon_type': 'light', 'weapon_profile': 'holy_rod',
        'rarity': 'uncommon',
        'damage_min': 9, 'damage_max': 14, 'defense': 0, 'weight': 2,
        'req_level': 3, 'req_strength': 0, 'req_agility': 0,
        'req_intuition': 0, 'req_wisdom': 5,
        'buy_price': 290, 'sell_price': 75,
        'skills_json': '[]', 'stat_bonus_json': '{"wisdom": 2}',
    },
    'tome': {
        'item_id': 'tome', 'name': '📚 Том чародея',
        'description': 'Гримуар поддержки и смешанных школ. Даёт гибкость, а не максимальный профиль.',
        'item_type': 'weapon', 'weapon_type': 'magic', 'weapon_profile': 'tome',
        'rarity': 'uncommon',
        'damage_min': 8, 'damage_max': 13, 'defense': 0, 'weight': 2,
        'req_level': 3, 'req_strength': 0, 'req_agility': 0,
        'req_intuition': 3, 'req_wisdom': 3,
        'buy_price': 285, 'sell_price': 72,
        'skills_json': '[]', 'stat_bonus_json': '{"intuition": 1, "wisdom": 1}',
    },
    'dagger': {
        'item_id': 'dagger', 'name': '🗡️ Кинжал',
        'description': 'Быстрый и лёгкий кинжал.',
        'item_type': 'weapon', 'weapon_type': 'melee', 'weapon_profile': 'daggers',
        'rarity': 'common',
        'damage_min': 7, 'damage_max': 11, 'defense': 0, 'weight': 1,
        'req_level': 1, 'req_strength': 0, 'req_agility': 3,
        'req_intuition': 0, 'req_wisdom': 0,
        'buy_price': 60, 'sell_price': 15,
        'skills_json': '[]', 'stat_bonus_json': '{"agility": 2}',
    },

    # ── БРОНЯ ────────────────────────────────────────────────

    'leather_armor': {
        'item_id': 'leather_armor', 'name': '🥋 Кожаная броня',
        'description': 'Лёгкая броня из кожи.',
        'item_type': 'armor', 'weapon_type': None, 'armor_class': 'medium',
        'rarity': 'common',
        'damage_min': 0, 'damage_max': 0, 'defense': 5, 'weight': 4,
        'req_level': 1, 'req_strength': 0, 'req_agility': 0,
        'req_intuition': 0, 'req_wisdom': 0,
        'buy_price': 100, 'sell_price': 25,
        'skills_json': '[]', 'stat_bonus_json': '{}',
    },
    'iron_shield': {
        'item_id': 'iron_shield', 'name': '🛡️ Железный щит',
        'description': 'Надёжная защита.',
        'item_type': 'armor', 'weapon_type': None, 'slot_identity': 'offhand',
        'offhand_profile': 'shield', 'encumbrance': 2,
        'rarity': 'common',
        'damage_min': 0, 'damage_max': 0, 'defense': 8, 'weight': 6,
        'req_level': 3, 'req_strength': 5, 'req_agility': 0,
        'req_intuition': 0, 'req_wisdom': 0,
        'buy_price': 180, 'sell_price': 45,
        'skills_json': '[]', 'stat_bonus_json': '{"vitality": 1}',
    },
    'oak_guard_shield': {
        'item_id': 'oak_guard_shield', 'name': '🛡️ Щит дубового дозора',
        'description': 'Солидный щит из дуба. Даёт выживание и базовый блок.',
        'item_type': 'armor', 'weapon_type': None, 'slot_identity': 'offhand',
        'offhand_profile': 'shield',
        'rarity': 'uncommon',
        'damage_min': 0, 'damage_max': 0, 'defense': 10, 'weight': 7,
        'req_level': 4, 'req_strength': 6, 'req_agility': 0,
        'req_intuition': 0, 'req_wisdom': 0,
        'buy_price': 260, 'sell_price': 70,
        'skills_json': '[]', 'stat_bonus_json': '{"max_hp": 20}',
    },
    'warden_kite_shield': {
        'item_id': 'warden_kite_shield', 'name': '🛡️ Каплевидный щит стража',
        'description': 'Щит городской стражи с упором на живучесть и устойчивость.',
        'item_type': 'armor', 'weapon_type': None, 'slot_identity': 'offhand',
        'offhand_profile': 'shield',
        'rarity': 'rare',
        'damage_min': 0, 'damage_max': 0, 'defense': 13, 'weight': 8,
        'req_level': 7, 'req_strength': 8, 'req_agility': 0,
        'req_intuition': 0, 'req_wisdom': 0,
        'buy_price': 420, 'sell_price': 120,
        'skills_json': '[]', 'stat_bonus_json': '{"vitality": 2, "physical_defense": 4}',
    },
    'apprentice_focus_orb': {
        'item_id': 'apprentice_focus_orb', 'name': '🔮 Фокус ученика',
        'description': 'Простой магический фокус для ранних кастеров.',
        'item_type': 'armor', 'weapon_type': None, 'slot_identity': 'offhand',
        'offhand_profile': 'focus',
        'rarity': 'uncommon',
        'damage_min': 0, 'damage_max': 0, 'defense': 3, 'weight': 2,
        'req_level': 3, 'req_strength': 0, 'req_agility': 0,
        'req_intuition': 3, 'req_wisdom': 0,
        'buy_price': 180, 'sell_price': 48,
        'skills_json': '[]', 'stat_bonus_json': '{"max_mana": 15}',
    },
    'azure_focus_prism': {
        'item_id': 'azure_focus_prism', 'name': '🔷 Лазурная призма фокуса',
        'description': 'Кристалл подгоняет темп заклинаний и усиливает пробой магии.',
        'item_type': 'armor', 'weapon_type': None, 'slot_identity': 'offhand',
        'offhand_profile': 'focus',
        'rarity': 'rare',
        'damage_min': 0, 'damage_max': 0, 'defense': 4, 'weight': 2,
        'req_level': 7, 'req_strength': 0, 'req_agility': 0,
        'req_intuition': 8, 'req_wisdom': 0,
        'buy_price': 430, 'sell_price': 128,
        'skills_json': '[]', 'stat_bonus_json': '{"magic_power": 4, "cast_tempo": 2}',
    },
    'novice_censer': {
        'item_id': 'novice_censer', 'name': '🕯️ Кадило послушника',
        'description': 'Учебное кадило с мягким бонусом к поддержке и мане.',
        'item_type': 'armor', 'weapon_type': None, 'slot_identity': 'offhand',
        'offhand_profile': 'censer',
        'rarity': 'uncommon',
        'damage_min': 0, 'damage_max': 0, 'defense': 3, 'weight': 2,
        'req_level': 3, 'req_strength': 0, 'req_agility': 0,
        'req_intuition': 0, 'req_wisdom': 3,
        'buy_price': 175, 'sell_price': 46,
        'skills_json': '[]', 'stat_bonus_json': '{"healing_power": 3}',
    },
    'choir_censer': {
        'item_id': 'choir_censer', 'name': '🕯️ Кадило храмового хора',
        'description': 'Укрепляет поддержку группы и даёт запас ресурса в долгих боях.',
        'item_type': 'armor', 'weapon_type': None, 'slot_identity': 'offhand',
        'offhand_profile': 'censer',
        'rarity': 'rare',
        'damage_min': 0, 'damage_max': 0, 'defense': 4, 'weight': 2,
        'req_level': 7, 'req_strength': 0, 'req_agility': 0,
        'req_intuition': 0, 'req_wisdom': 8,
        'buy_price': 425, 'sell_price': 124,
        'skills_json': '[]', 'stat_bonus_json': '{"healing_power": 4, "buff_power": 3}',
    },
    'militia_cuirass': {
        'item_id': 'militia_cuirass', 'name': '🛡️ Кираса ополченца',
        'description': 'Тяжёлый нагрудник для фронтлайна и разменов.',
        'item_type': 'armor', 'weapon_type': None, 'slot_identity': 'chest', 'armor_class': 'heavy',
        'rarity': 'common',
        'damage_min': 0, 'damage_max': 0, 'defense': 9, 'weight': 8,
        'req_level': 4, 'req_strength': 5, 'req_agility': 0,
        'req_intuition': 0, 'req_wisdom': 0,
        'buy_price': 220, 'sell_price': 58,
        'skills_json': '[]', 'stat_bonus_json': '{}',
    },
    'tracker_jacket': {
        'item_id': 'tracker_jacket', 'name': '🥋 Куртка следопыта',
        'description': 'Средняя броня для мобильного физического боя.',
        'item_type': 'armor', 'weapon_type': None, 'slot_identity': 'chest', 'armor_class': 'medium',
        'rarity': 'rare',
        'damage_min': 0, 'damage_max': 0, 'defense': 7, 'weight': 5,
        'req_level': 4, 'req_strength': 0, 'req_agility': 5,
        'req_intuition': 0, 'req_wisdom': 0,
        'buy_price': 240, 'sell_price': 64,
        'skills_json': '[]', 'stat_bonus_json': '{"accuracy": 3, "evasion": 2}',
    },
    'acolyte_robe': {
        'item_id': 'acolyte_robe', 'name': '🧥 Роба аколита',
        'description': 'Лёгкое одеяние для кастеров и поддержки.',
        'item_type': 'armor', 'weapon_type': None, 'slot_identity': 'chest', 'armor_class': 'light',
        'rarity': 'uncommon',
        'damage_min': 0, 'damage_max': 0, 'defense': 5, 'weight': 3,
        'req_level': 4, 'req_strength': 0, 'req_agility': 0,
        'req_intuition': 0, 'req_wisdom': 4,
        'buy_price': 210, 'sell_price': 56,
        'skills_json': '[]', 'stat_bonus_json': '{"max_mana": 20}',
    },
    'band_of_precision': {
        'item_id': 'band_of_precision', 'name': '💍 Кольцо точности',
        'description': 'Аксессуар стрелков и дуэлянтов: чистая меткость и темп.',
        'item_type': 'accessory', 'weapon_type': None, 'slot_identity': 'ring',
        'rarity': 'rare',
        'damage_min': 0, 'damage_max': 0, 'defense': 0, 'weight': 1,
        'req_level': 5, 'req_strength': 0, 'req_agility': 4,
        'req_intuition': 0, 'req_wisdom': 0,
        'buy_price': 260, 'sell_price': 72,
        'skills_json': '[]', 'stat_bonus_json': '{"accuracy": 3, "agility": 1}',
    },
    'ring_of_quiet_mind': {
        'item_id': 'ring_of_quiet_mind', 'name': '💍 Кольцо тихого разума',
        'description': 'Стабилизирует ману и поддерживает ритм заклинаний.',
        'item_type': 'accessory', 'weapon_type': None, 'slot_identity': 'ring',
        'rarity': 'rare',
        'damage_min': 0, 'damage_max': 0, 'defense': 0, 'weight': 1,
        'req_level': 5, 'req_strength': 0, 'req_agility': 0,
        'req_intuition': 3, 'req_wisdom': 3,
        'buy_price': 255, 'sell_price': 70,
        'skills_json': '[]', 'stat_bonus_json': '{"max_mana": 16, "wisdom": 1}',
    },
    'amulet_of_kindled_prayer': {
        'item_id': 'amulet_of_kindled_prayer', 'name': '📿 Амулет теплой молитвы',
        'description': 'Скромный амулет поддержки с упором в лечение и стойкость.',
        'item_type': 'accessory', 'weapon_type': None, 'slot_identity': 'amulet',
        'rarity': 'rare',
        'damage_min': 0, 'damage_max': 0, 'defense': 0, 'weight': 1,
        'req_level': 7, 'req_strength': 0, 'req_agility': 0,
        'req_intuition': 0, 'req_wisdom': 8,
        'buy_price': 430, 'sell_price': 126,
        'skills_json': '[]', 'stat_bonus_json': '{"wisdom": 2, "healing_power": 4}',
    },
    'dual_path_loop': {
        'item_id': 'dual_path_loop', 'name': '💍 Петля двойного пути',
        'description': 'Гибридное кольцо без экстремумов: немного магии и немного темпа.',
        'item_type': 'accessory', 'weapon_type': None, 'slot_identity': 'ring',
        'rarity': 'rare',
        'damage_min': 0, 'damage_max': 0, 'defense': 0, 'weight': 1,
        'req_level': 7, 'req_strength': 0, 'req_agility': 0,
        'req_intuition': 5, 'req_wisdom': 0,
        'buy_price': 420, 'sell_price': 122,
        'skills_json': '[]', 'stat_bonus_json': '{"magic_power": 3, "accuracy": 2}',
    },

    # ── ЗЕЛЬЯ ────────────────────────────────────────────────

    'health_potion_small': {
        'item_id': 'health_potion_small', 'name': '🧪 Малое зелье HP',
        'description': 'Восстанавливает 30 HP.',
        'item_type': 'potion', 'weapon_type': None,
        'rarity': 'common',
        'damage_min': 0, 'damage_max': 0, 'defense': 0, 'weight': 1,
        'req_level': 1, 'req_strength': 0, 'req_agility': 0,
        'req_intuition': 0, 'req_wisdom': 0,
        'buy_price': 30, 'sell_price': 5,
        'skills_json': '[]', 'stat_bonus_json': '{"heal": 30}',
    },
    'health_potion': {
        'item_id': 'health_potion', 'name': '❤️ Зелье HP',
        'description': 'Восстанавливает 80 HP.',
        'item_type': 'potion', 'weapon_type': None,
        'rarity': 'common',
        'damage_min': 0, 'damage_max': 0, 'defense': 0, 'weight': 1,
        'req_level': 1, 'req_strength': 0, 'req_agility': 0,
        'req_intuition': 0, 'req_wisdom': 0,
        'buy_price': 80, 'sell_price': 15,
        'skills_json': '[]', 'stat_bonus_json': '{"heal": 80}',
    },
    'mana_potion': {
        'item_id': 'mana_potion', 'name': '🔵 Зелье маны',
        'description': 'Восстанавливает 50 маны.',
        'item_type': 'potion', 'weapon_type': None,
        'rarity': 'common',
        'damage_min': 0, 'damage_max': 0, 'defense': 0, 'weight': 1,
        'req_level': 1, 'req_strength': 0, 'req_agility': 0,
        'req_intuition': 0, 'req_wisdom': 0,
        'buy_price': 60, 'sell_price': 12,
        'skills_json': '[]', 'stat_bonus_json': '{"mana": 50}',
    },

    # ── МАТЕРИАЛЫ ────────────────────────────────────────────

    'wolf_pelt':    {'item_id': 'wolf_pelt',    'name': '🐺 Шкура волка',     'description': 'Материал для крафта.', 'item_type': 'material', 'weapon_type': None, 'rarity': 'common', 'damage_min': 0, 'damage_max': 0, 'defense': 0, 'weight': 1, 'req_level': 1, 'req_strength': 0, 'req_agility': 0, 'req_intuition': 0, 'req_wisdom': 0, 'buy_price': 0, 'sell_price': 8,  'skills_json': '[]', 'stat_bonus_json': '{}'},
    'wolf_fang':    {'item_id': 'wolf_fang',    'name': '🦷 Клык волка',      'description': 'Острый клык.', 'item_type': 'material', 'weapon_type': None, 'rarity': 'common', 'damage_min': 0, 'damage_max': 0, 'defense': 0, 'weight': 1, 'req_level': 1, 'req_strength': 0, 'req_agility': 0, 'req_intuition': 0, 'req_wisdom': 0, 'buy_price': 0, 'sell_price': 12, 'skills_json': '[]', 'stat_bonus_json': '{}'},
    'boar_meat':    {'item_id': 'boar_meat',    'name': '🥩 Мясо кабана',     'description': 'Съедобное мясо.', 'item_type': 'material', 'weapon_type': None, 'rarity': 'common', 'damage_min': 0, 'damage_max': 0, 'defense': 0, 'weight': 2, 'req_level': 1, 'req_strength': 0, 'req_agility': 0, 'req_intuition': 0, 'req_wisdom': 0, 'buy_price': 0, 'sell_price': 5,  'skills_json': '[]', 'stat_bonus_json': '{}'},
    'boar_tusk':    {'item_id': 'boar_tusk',    'name': '🐗 Бивень кабана',   'description': 'Прочный бивень.', 'item_type': 'material', 'weapon_type': None, 'rarity': 'common', 'damage_min': 0, 'damage_max': 0, 'defense': 0, 'weight': 1, 'req_level': 1, 'req_strength': 0, 'req_agility': 0, 'req_intuition': 0, 'req_wisdom': 0, 'buy_price': 0, 'sell_price': 10, 'skills_json': '[]', 'stat_bonus_json': '{}'},
    'spider_silk':  {'item_id': 'spider_silk',  'name': '🕸️ Паучий шёлк',    'description': 'Прочная нить.', 'item_type': 'material', 'weapon_type': None, 'rarity': 'uncommon', 'damage_min': 0, 'damage_max': 0, 'defense': 0, 'weight': 1, 'req_level': 1, 'req_strength': 0, 'req_agility': 0, 'req_intuition': 0, 'req_wisdom': 0, 'buy_price': 0, 'sell_price': 18, 'skills_json': '[]', 'stat_bonus_json': '{}'},
    'spider_venom': {'item_id': 'spider_venom', 'name': '☠️ Яд паука',        'description': 'Используется в крафте зелий.', 'item_type': 'material', 'weapon_type': None, 'rarity': 'uncommon', 'damage_min': 0, 'damage_max': 0, 'defense': 0, 'weight': 1, 'req_level': 1, 'req_strength': 0, 'req_agility': 0, 'req_intuition': 0, 'req_wisdom': 0, 'buy_price': 0, 'sell_price': 25, 'skills_json': '[]', 'stat_bonus_json': '{}'},
    'ancient_bark': {'item_id': 'ancient_bark', 'name': '🪵 Древняя кора',    'description': 'Редкий материал.', 'item_type': 'material', 'weapon_type': None, 'rarity': 'uncommon', 'damage_min': 0, 'damage_max': 0, 'defense': 0, 'weight': 2, 'req_level': 1, 'req_strength': 0, 'req_agility': 0, 'req_intuition': 0, 'req_wisdom': 0, 'buy_price': 0, 'sell_price': 30, 'skills_json': '[]', 'stat_bonus_json': '{}'},
    'treant_heart': {'item_id': 'treant_heart', 'name': '💚 Сердце трента',   'description': 'Пульсирует древней силой.', 'item_type': 'material', 'weapon_type': None, 'rarity': 'rare', 'damage_min': 0, 'damage_max': 0, 'defense': 0, 'weight': 1, 'req_level': 1, 'req_strength': 0, 'req_agility': 0, 'req_intuition': 0, 'req_wisdom': 0, 'buy_price': 0, 'sell_price': 80, 'skills_json': '[]', 'stat_bonus_json': '{}'},
    'iron_ore':     {'item_id': 'iron_ore',     'name': '⛏️ Железная руда',  'description': 'Руда для крафта.', 'item_type': 'material', 'weapon_type': None, 'rarity': 'common', 'damage_min': 0, 'damage_max': 0, 'defense': 0, 'weight': 3, 'req_level': 1, 'req_strength': 0, 'req_agility': 0, 'req_intuition': 0, 'req_wisdom': 0, 'buy_price': 0, 'sell_price': 6,  'skills_json': '[]', 'stat_bonus_json': '{}'},
    'goblin_ear':   {'item_id': 'goblin_ear',   'name': '👺 Ухо гоблина',     'description': 'Квестовый предмет.', 'item_type': 'material', 'weapon_type': None, 'rarity': 'common', 'damage_min': 0, 'damage_max': 0, 'defense': 0, 'weight': 1, 'req_level': 1, 'req_strength': 0, 'req_agility': 0, 'req_intuition': 0, 'req_wisdom': 0, 'buy_price': 0, 'sell_price': 7,  'skills_json': '[]', 'stat_bonus_json': '{}'},
    'bat_wing':     {'item_id': 'bat_wing',     'name': '🦇 Крыло летучей мыши', 'description': 'Материал для зелий.', 'item_type': 'material', 'weapon_type': None, 'rarity': 'common', 'damage_min': 0, 'damage_max': 0, 'defense': 0, 'weight': 1, 'req_level': 1, 'req_strength': 0, 'req_agility': 0, 'req_intuition': 0, 'req_wisdom': 0, 'buy_price': 0, 'sell_price': 9,  'skills_json': '[]', 'stat_bonus_json': '{}'},
    'stone_core':   {'item_id': 'stone_core',   'name': '🗿 Каменное ядро',   'description': 'Магический кристалл голема.', 'item_type': 'material', 'weapon_type': None, 'rarity': 'rare', 'damage_min': 0, 'damage_max': 0, 'defense': 0, 'weight': 3, 'req_level': 1, 'req_strength': 0, 'req_agility': 0, 'req_intuition': 0, 'req_wisdom': 0, 'buy_price': 0, 'sell_price': 60, 'skills_json': '[]', 'stat_bonus_json': '{}'},
    'rat_tail':     {'item_id': 'rat_tail',     'name': '🐀 Хвост крысы',     'description': 'Квестовый предмет.', 'item_type': 'material', 'weapon_type': None, 'rarity': 'common', 'damage_min': 0, 'damage_max': 0, 'defense': 0, 'weight': 1, 'req_level': 1, 'req_strength': 0, 'req_agility': 0, 'req_intuition': 0, 'req_wisdom': 0, 'buy_price': 0, 'sell_price': 4,  'skills_json': '[]', 'stat_bonus_json': '{}'},
    'worn_pickaxe': {'item_id': 'worn_pickaxe', 'name': '⛏️ Сломанная кирка', 'description': 'Почти бесполезна.', 'item_type': 'material', 'weapon_type': None, 'rarity': 'common', 'damage_min': 0, 'damage_max': 0, 'defense': 0, 'weight': 3, 'req_level': 1, 'req_strength': 0, 'req_agility': 0, 'req_intuition': 0, 'req_wisdom': 0, 'buy_price': 0, 'sell_price': 3,  'skills_json': '[]', 'stat_bonus_json': '{}'},
    'coal':         {'item_id': 'coal',         'name': '🪨 Уголь',           'description': 'Топливо для кузни.', 'item_type': 'material', 'weapon_type': None, 'rarity': 'common', 'damage_min': 0, 'damage_max': 0, 'defense': 0, 'weight': 2, 'req_level': 1, 'req_strength': 0, 'req_agility': 0, 'req_intuition': 0, 'req_wisdom': 0, 'buy_price': 0, 'sell_price': 4,  'skills_json': '[]', 'stat_bonus_json': '{}'},
    'gem_common':   {'item_id': 'gem_common',   'name': '💎 Обычный камень',  'description': 'Используется в крафте.', 'item_type': 'material', 'weapon_type': None, 'rarity': 'uncommon', 'damage_min': 0, 'damage_max': 0, 'defense': 0, 'weight': 1, 'req_level': 1, 'req_strength': 0, 'req_agility': 0, 'req_intuition': 0, 'req_wisdom': 0, 'buy_price': 0, 'sell_price': 35, 'skills_json': '[]', 'stat_bonus_json': '{}'},
    'golem_fragment':{'item_id':'golem_fragment','name': '🗿 Фрагмент голема', 'description': 'Прочный материал.', 'item_type': 'material', 'weapon_type': None, 'rarity': 'uncommon', 'damage_min': 0, 'damage_max': 0, 'defense': 0, 'weight': 2, 'req_level': 1, 'req_strength': 0, 'req_agility': 0, 'req_intuition': 0, 'req_wisdom': 0, 'buy_price': 0, 'sell_price': 22, 'skills_json': '[]', 'stat_bonus_json': '{}'},
    'rat_fur':      {'item_id': 'rat_fur',      'name': '🐀 Шкура крысы',     'description': 'Дешёвый материал.', 'item_type': 'material', 'weapon_type': None, 'rarity': 'common', 'damage_min': 0, 'damage_max': 0, 'defense': 0, 'weight': 1, 'req_level': 1, 'req_strength': 0, 'req_agility': 0, 'req_intuition': 0, 'req_wisdom': 0, 'buy_price': 0, 'sell_price': 3,  'skills_json': '[]', 'stat_bonus_json': '{}'},
    'herb_common':  {'item_id': 'herb_common',  'name': '🌿 Обычная трава',    'description': 'Материал для крафта.', 'item_type': 'material', 'weapon_type': None, 'rarity': 'common',   'damage_min': 0, 'damage_max': 0, 'defense': 0, 'weight': 1, 'req_level': 1, 'req_strength': 0, 'req_agility': 0, 'req_intuition': 0, 'req_wisdom': 0, 'buy_price': 0, 'sell_price': 3,  'skills_json': '[]', 'stat_bonus_json': '{}'},
    'herb_magic':   {'item_id': 'herb_magic',   'name': '✨ Магическая трава',  'description': 'Редкий магический ингредиент.', 'item_type': 'material', 'weapon_type': None, 'rarity': 'uncommon', 'damage_min': 0, 'damage_max': 0, 'defense': 0, 'weight': 1, 'req_level': 1, 'req_strength': 0, 'req_agility': 0, 'req_intuition': 0, 'req_wisdom': 0, 'buy_price': 0, 'sell_price': 12, 'skills_json': '[]', 'stat_bonus_json': '{}'},
    'wood_dark':    {'item_id': 'wood_dark',    'name': '🌑 Тёмное дерево',    'description': 'Древесина из тёмного леса.', 'item_type': 'material', 'weapon_type': None, 'rarity': 'uncommon', 'damage_min': 0, 'damage_max': 0, 'defense': 0, 'weight': 2, 'req_level': 1, 'req_strength': 0, 'req_agility': 0, 'req_intuition': 0, 'req_wisdom': 0, 'buy_price': 0, 'sell_price': 10, 'skills_json': '[]', 'stat_bonus_json': '{}'},
}

def get_item(item_id: str) -> dict:
    return ITEMS.get(item_id)


def get_item_metadata(item_id: str) -> dict:
    """Normalized archetype metadata for equipment-related systems."""
    return get_item_archetype_metadata(get_item(item_id))


def get_item_encumbrance(item: dict | None) -> int | None:
    """Возвращает semantic encumbrance или fallback на вес предмета."""
    if not item:
        return None
    return item.get('encumbrance', item.get('weight'))

print(f'✅ game/items_data.py создан! Предметов: {len(ITEMS)}')
