# ============================================================
# skills.py — все скиллы и деревья навыков
# ============================================================

# Структура скилла:
# id, name, description, weapon_id, branch (A/B),
# unlock_mastery (уровень владения для открытия),
# max_level, mana_cost, cooldown (ходы),
# type: damage/heal/buff/debuff/control,
# scale_stat, scale_mult, base_value, level_bonus
# duration — для баффов: кол-во ходов (не зависит от base_value)

SKILLS = {

    # ════════════════════════════════════════
    # БАЗОВЫЕ СКИЛЛЫ — есть у ВСЕХ оружий
    # ════════════════════════════════════════

    'power_strike': {
        'id':             'power_strike',
        'name':           '💢 Мощный удар',
        'description':    'Наносит 150% урона оружием.',
        'weapon_id':      'base',
        'branch':         'base',
        'unlock_mastery': 0,
        'max_level':      5,
        'mana_cost':      15,
        'cooldown':       2,
        'type':           'damage',
        'scale_stat':     None,
        'scale_mult':     0,
        'base_value':     150,
        'level_bonus':    0.15,
    },
    'defensive_stance': {
        'id':             'defensive_stance',
        'name':           '🛡️ Защитная стойка',
        'description':    'Стойка передовой: сильно снижает входящий урон и помогает держать линию.',
        'weapon_id':      'sword_1h',
        'branch':         'A',
        'unlock_mastery': 2,
        'max_level':      5,
        'mana_cost':      10,
        'cooldown':       3,
        'type':           'buff',
        'scale_stat':     'vitality',
        'scale_mult':     0.5,
        'base_value':     40,
        'duration':       2,
        'level_bonus':    0.05,
    },

    # ════════════════════════════════════════
    # ⚔️ ЖЕЛЕЗНЫЙ МЕЧ / ДЕРЕВЯННЫЙ МЕЧ
    # ════════════════════════════════════════

    # Ветка A — Guardian
    'sword_rush': {
        'id':             'sword_rush',
        'name':           '⚡ Рывок',
        'description':    'Дисциплинированный рывок в атаку: наносит урон и открывает цель под давление.',
        'weapon_id':      'iron_sword',
        'branch':         'A',
        'unlock_mastery': 1,
        'max_level':      5,
        'mana_cost':      20,
        'cooldown':       4,
        'type':           'damage',
        'scale_stat':     'strength',
        'scale_mult':     1.5,
        'base_value':     110,
        'level_bonus':    0.12,
    },
    'shield_bash': {
        'id':             'shield_bash',
        'name':           '🛡️ Удар щитом',
        'description':    'Короткий контроль: наносит небольшой урон, сбивает баланс и ослабляет урон врага.',
        'weapon_id':      'iron_sword',
        'branch':         'A',
        'unlock_mastery': 4,
        'max_level':      5,
        'mana_cost':      16,
        'cooldown':       3,
        'type':           'debuff',
        'scale_stat':     'vitality',
        'scale_mult':     0.7,
        'base_value':     26,
        'duration':       2,
        'level_bonus':    0.08,
    },

    # Ветка B — Vanguard
    'driving_slash': {
        'id':             'driving_slash',
        'name':           '⚔️ Продавливающий удар',
        'description':    'Наступающий удар для начала давления.',
        'weapon_id':      'iron_sword',
        'branch':         'B',
        'unlock_mastery': 1,
        'max_level':      5,
        'mana_cost':      18,
        'cooldown':       3,
        'type':           'damage',
        'scale_stat':     'strength',
        'scale_mult':     1.4,
        'base_value':     120,
        'level_bonus':    0.11,
    },
    'expose_guard': {
        'id':             'expose_guard',
        'name':           '🎯 Вскрытие защиты',
        'description':    'Открывает брешь в защите цели, усиливая последующие удары по ней.',
        'weapon_id':      'iron_sword',
        'branch':         'B',
        'unlock_mastery': 3,
        'max_level':      5,
        'mana_cost':      16,
        'cooldown':       3,
        'type':           'debuff',
        'scale_stat':     'agility',
        'scale_mult':     0.7,
        'base_value':     24,
        'duration':       2,
        'level_bonus':    0.07,
    },
    'press_the_line': {
        'id':             'press_the_line',
        'name':           '📣 Дави строй',
        'description':    'Короткое окно наступления: временно усиливает твой прямой урон.',
        'weapon_id':      'iron_sword',
        'branch':         'B',
        'unlock_mastery': 5,
        'max_level':      5,
        'mana_cost':      20,
        'cooldown':       4,
        'type':           'buff',
        'scale_stat':     'strength',
        'scale_mult':     0.6,
        'base_value':     16,
        'duration':       2,
        'level_bonus':    0.08,
    },
    'punishing_cut': {
        'id':             'punishing_cut',
        'name':           '🩸 Карательный разрез',
        'description':    'Базово наносит урон. Получает payoff по уязвимой цели или в темп-окно Press the Line.',
        'weapon_id':      'iron_sword',
        'branch':         'B',
        'unlock_mastery': 7,
        'max_level':      5,
        'mana_cost':      24,
        'cooldown':       4,
        'type':           'damage',
        'scale_stat':     'strength',
        'scale_mult':     1.7,
        'base_value':     150,
        'level_bonus':    0.12,
        'payoff_vulnerable_mult': 1.35,
        'payoff_press_line_mult': 1.20,
        'payoff_combined_mult':   1.45,
    },
    'vanguard_surge': {
        'id':             'vanguard_surge',
        'name':           '🚩 Натиск авангарда',
        'description':    'Ключевой финишер ветки: максимально силён в окно вскрытой защиты и темпа.',
        'weapon_id':      'iron_sword',
        'branch':         'B',
        'unlock_mastery': 10,
        'max_level':      5,
        'mana_cost':      36,
        'cooldown':       6,
        'type':           'damage',
        'scale_stat':     'strength',
        'scale_mult':     2.1,
        'base_value':     190,
        'level_bonus':    0.14,
    },
    'parry': {
        'id':             'parry',
        'name':           '🔄 Парирование',
        'description':    'Отражает следующую атаку врага. Со щитом отражение сильнее, но щит не обязателен.',
        'weapon_id':      'iron_sword',
        'branch':         'A',
        'unlock_mastery': 1,
        'max_level':      5,
        'mana_cost':      20,
        'cooldown':       4,
        'type':           'buff',
        'scale_stat':     'vitality',
        'scale_mult':     0.35,
        'base_value':     1.0,
        'duration':       1,
        'level_bonus':    0.1,
    },
    'disarm': {
        'id':             'disarm',
        'name':           '🤺 Обезоруживание',
        'description':    'Снижает урон врага на 40% на 2 хода.',
        'weapon_id':      'iron_sword',
        'branch':         'B',
        'unlock_mastery': 3,
        'max_level':      5,
        'mana_cost':      20,
        'cooldown':       3,
        'type':           'debuff',
        'scale_stat':     'agility',
        'scale_mult':     0.8,
        'base_value':     40,
        'level_bonus':    0.08,
    },
    'counter': {
        'id':             'counter',
        'name':           '⚔️ Контратака',
        'description':    'Пассивно: при получении урона есть шанс на ответный удар. По открытой цели бьёт сильнее, а в защитном размене срабатывает надёжнее и бьёт плотнее.',
        'weapon_id':      'iron_sword',
        'branch':         'A',
        'unlock_mastery': 4,
        'max_level':      5,
        'mana_cost':      0,
        'cooldown':       0,
        'type':           'passive',
        'scale_stat':     'vitality',
        'scale_mult':     0.8,
        'base_value':     30,
        'level_bonus':    0.05,
        'payoff_opened_mult': 1.30,
        'payoff_defense_setup_mult': 1.10,
        'payoff_opened_defense_mult': 1.40,
    },
    'sword_ultimate_b': {
        'id':             'sword_ultimate_b',
        'name':           '🌟 Непробиваемый',
        'description':    'На 3 хода становишься неуязвимым. Получаешь 0 урона.',
        'weapon_id':      'iron_sword',
        'branch':         'B',
        'unlock_mastery': 10,
        'max_level':      5,
        'mana_cost':      60,
        'cooldown':       8,
        'type':           'buff',
        'scale_stat':     'vitality',
        'scale_mult':     0.5,
        'base_value':     3,
        'duration':       3,
        'level_bonus':    0.2,
    },

    # ════════════════════════════════════════
    # 🗡️ КИНЖАЛ
    # ════════════════════════════════════════

    # Ветка A — Яды
    'poison_blade': {
        'id':             'poison_blade',
        'name':           '☠️ Ядовитый клинок',
        'description':    'Отравляет врага. 25% урона в ход на 3 хода.',
        'weapon_id':      'dagger',
        'branch':         'A',
        'unlock_mastery': 1,
        'max_level':      5,
        'mana_cost':      15,
        'cooldown':       3,
        'type':           'debuff',
        'scale_stat':     'agility',
        'scale_mult':     0.8,
        'base_value':     25,
        'level_bonus':    0.15,
        'effect':         ('poison', 1.0, 3),
    },
    'envenom': {
        'id':             'envenom',
        'name':           '🐍 Змеиный яд',
        'description':    'Усиливает яд. Следующее отравление наносит двойной урон.',
        'weapon_id':      'dagger',
        'branch':         'A',
        'unlock_mastery': 3,
        'max_level':      5,
        'mana_cost':      20,
        'cooldown':       4,
        'type':           'buff',
        'scale_stat':     'agility',
        'scale_mult':     1.0,
        'base_value':     2.0,
        'duration':       2,
        'level_bonus':    0.1,
    },
    'venom_storm': {
        'id':             'venom_storm',
        'name':           '💀 Смертельный яд',
        'description':    'Накладывает стек из 3 ядов одновременно.',
        'weapon_id':      'dagger',
        'branch':         'A',
        'unlock_mastery': 6,
        'max_level':      5,
        'mana_cost':      35,
        'cooldown':       5,
        'type':           'debuff',
        'scale_stat':     'agility',
        'scale_mult':     1.2,
        'base_value':     20,
        'level_bonus':    0.12,
        'effect':         ('poison', 1.0, 3),
    },
    'dagger_ult_a': {
        'id':             'dagger_ult_a',
        'name':           '🕷️ Паучье гнездо',
        'description':    'Ультимативный яд. 60% урона в ход на 5 ходов. Нельзя снять.',
        'weapon_id':      'dagger',
        'branch':         'A',
        'unlock_mastery': 10,
        'max_level':      5,
        'mana_cost':      60,
        'cooldown':       8,
        'type':           'debuff',
        'scale_stat':     'agility',
        'scale_mult':     2.0,
        'base_value':     60,
        'level_bonus':    0.15,
        'effect':         ('poison', 1.0, 5),
    },
    'envenom_blades': {
        'id':             'envenom_blades',
        'name':           '🐍 Отравленные клинки',
        'description':    'Подготавливает усиленный яд: следующее успешное отравление будет сильнее.',
        'weapon_id':      'dagger',
        'branch':         'A',
        'unlock_mastery': 1,
        'max_level':      5,
        'mana_cost':      16,
        'cooldown':       3,
        'type':           'buff',
        'scale_stat':     'agility',
        'scale_mult':     0.6,
        'base_value':     1.0,
        'duration':       2,
        'level_bonus':    0.1,
        'poison_bonus_mult': 1.8,
        'poison_bonus_turns': 1,
    },
    'toxic_cut': {
        'id':             'toxic_cut',
        'name':           '☠️ Токсичный разрез',
        'description':    'Наносит прямой урон и гарантированно накладывает 1 стак яда.',
        'weapon_id':      'dagger',
        'branch':         'A',
        'unlock_mastery': 3,
        'max_level':      5,
        'mana_cost':      18,
        'cooldown':       2,
        'type':           'damage',
        'scale_stat':     'agility',
        'scale_mult':     1.4,
        'base_value':     115,
        'level_bonus':    0.1,
        'poison_base_ratio': 0.25,
        'poison_duration': 3,
    },
    'crippling_venom': {
        'id':             'crippling_venom',
        'name':           '🧪 Калечащий яд',
        'description':    'Ослабляет темп врага: режет урон и накладывает замедление.',
        'weapon_id':      'dagger',
        'branch':         'A',
        'unlock_mastery': 5,
        'max_level':      5,
        'mana_cost':      20,
        'cooldown':       3,
        'type':           'debuff',
        'scale_stat':     'agility',
        'scale_mult':     0.9,
        'base_value':     22,
        'duration':       2,
        'level_bonus':    0.08,
    },
    'widows_kiss': {
        'id':             'widows_kiss',
        'name':           '🕷️ Поцелуй вдовы',
        'description':    'Payoff-удар: сильнее по отравленной, ослабленной или вскрытой цели.',
        'weapon_id':      'dagger',
        'branch':         'A',
        'unlock_mastery': 7,
        'max_level':      5,
        'mana_cost':      24,
        'cooldown':       4,
        'type':           'damage',
        'scale_stat':     'agility',
        'scale_mult':     1.7,
        'base_value':     145,
        'level_bonus':    0.12,
        'payoff_poisoned_mult': 1.20,
        'payoff_weakened_mult': 1.20,
        'payoff_opened_mult': 1.20,
        'payoff_combined_mult': 1.26,
    },
    'rupture_toxins': {
        'id':             'rupture_toxins',
        'name':           '💥 Разрыв токсинов',
        'description':    'Финишер ветки Venom: усиливается от активных ядов и поглощает их.',
        'weapon_id':      'dagger',
        'branch':         'A',
        'unlock_mastery': 10,
        'max_level':      5,
        'mana_cost':      34,
        'cooldown':       6,
        'type':           'damage',
        'scale_stat':     'agility',
        'scale_mult':     2.0,
        'base_value':     170,
        'level_bonus':    0.14,
        'rupture_bonus_per_stack': 12,
        'rupture_bonus_from_poison_value_ratio': 0.30,
    },

    # Ветка B — Уклонение и крит
    'backstab': {
        'id':             'backstab',
        'name':           '🗡️ Удар в спину',
        'description':    'Сильный burst по открытой цели (замедление, контроль или сбитый баланс).',
        'weapon_id':      'dagger',
        'branch':         'B',
        'unlock_mastery': 7,
        'max_level':      5,
        'mana_cost':      20,
        'cooldown':       2,
        'type':           'damage',
        'scale_stat':     'agility',
        'scale_mult':     2.0,
        'base_value':     130,
        'level_bonus':    0.12,
    },
    'smoke_bomb': {
        'id':             'smoke_bomb',
        'name':           '💨 Дымовая завеса',
        'description':    'Короткое защитное окно уклонения на 1 ход: помогает пережить ответный ход.',
        'weapon_id':      'dagger',
        'branch':         'B',
        'unlock_mastery': 1,
        'max_level':      5,
        'mana_cost':      20,
        'cooldown':       4,
        'type':           'buff',
        'scale_stat':     'agility',
        'scale_mult':     0.5,
        'base_value':     35,
        'duration':       1,
        'level_bonus':    0.08,
    },
    'feint_step': {
        'id':             'feint_step',
        'name':           '👣 Ложный шаг',
        'description':    'Короткий setup-бафф для следующего темпового удара.',
        'weapon_id':      'dagger',
        'branch':         'B',
        'unlock_mastery': 3,
        'max_level':      5,
        'mana_cost':      14,
        'cooldown':       2,
        'type':           'buff',
        'scale_stat':     'agility',
        'scale_mult':     0.5,
        'base_value':     1.0,
        'duration':       1,
        'level_bonus':    0.08,
        'setup_runtime_turns': 2,
    },
    'quick_slice': {
        'id':             'quick_slice',
        'name':           '⚡ Быстрый срез',
        'description':    'Темповый удар с малым КД; после Ложного шага усиливается и замедляет цель.',
        'weapon_id':      'dagger',
        'branch':         'B',
        'unlock_mastery': 5,
        'max_level':      5,
        'mana_cost':      16,
        'cooldown':       2,
        'type':           'damage',
        'scale_stat':     'agility',
        'scale_mult':     1.3,
        'base_value':     105,
        'level_bonus':    0.1,
        'feint_payoff_mult': 1.20,
        'feint_slow_turns': 1,
    },
    'death_dance': {
        'id':             'death_dance',
        'name':           '💃 Смертельный танец',
        'description':    'Атакует 3 раза за ход. Каждый удар слабее но может крит.',
        'weapon_id':      'dagger',
        'branch':         'B',
        'unlock_mastery': 6,
        'max_level':      5,
        'mana_cost':      35,
        'cooldown':       4,
        'type':           'damage',
        'scale_stat':     'agility',
        'scale_mult':     1.5,
        'base_value':     80,
        'level_bonus':    0.1,
        'hits':           3,
    },
    'dagger_ult_b': {
        'id':             'dagger_ult_b',
        'name':           '👻 Тень смерти',
        'description':    'Телепортируется за спину врага. Следующие 3 атаки — гарантированный крит.',
        'weapon_id':      'dagger',
        'branch':         'B',
        'unlock_mastery': 10,
        'max_level':      5,
        'mana_cost':      55,
        'cooldown':       7,
        'type':           'buff',
        'scale_stat':     'luck',
        'scale_mult':     1.0,
        'base_value':     3,
        'duration':       3,
        'level_bonus':    0.2,
    },
    'shadow_chain': {
        'id':             'shadow_chain',
        'name':           '🌑 Цепь теней',
        'description':    'Финиширующая серия: сильнее по открытой цели и немного усиливается в evasive-окно.',
        'weapon_id':      'dagger',
        'branch':         'B',
        'unlock_mastery': 10,
        'max_level':      5,
        'mana_cost':      30,
        'cooldown':       5,
        'type':           'damage',
        'scale_stat':     'agility',
        'scale_mult':     1.8,
        'base_value':     90,
        'level_bonus':    0.12,
        'hits':           2,
        'opened_damage_mult': 1.50,
        'evasive_window_damage_mult': 1.12,
        'opened_evasive_damage_mult': 1.60,
    },

    # ════════════════════════════════════════
    # 🏹 КОРОТКИЙ ЛУК
    # ════════════════════════════════════════

    # Ветка A — Sniper
    'aimed_shot': {
        'id':             'aimed_shot',
        'name':           '🎯 Прицельный выстрел',
        'description':    'Точный снайперский выстрел: стабильное попадание, сильнее по отмеченной цели и в окно Твёрдого прицела.',
        'weapon_id':      'short_bow',
        'branch':         'A',
        'unlock_mastery': 3,
        'max_level':      5,
        'mana_cost':      25,
        'cooldown':       3,
        'type':           'damage',
        'scale_stat':     'intuition',
        'scale_mult':     2.0,
        'base_value':     200,
        'level_bonus':    0.12,
        'piercing':       True,
        'accuracy_bonus': 25,
        'steady_accuracy_bonus': 30,
        'marked_mult':    1.22,
        'steady_mult':    1.10,
        'marked_steady_mult': 1.30,
    },
    'hunters_mark': {
        'id':             'hunters_mark',
        'name':           '🔍 Метка охотника',
        'description':    'Помечает цель на несколько ходов: Sniper-payoff выстрелы по метке наносят больше урона.',
        'weapon_id':      'short_bow',
        'branch':         'A',
        'unlock_mastery': 1,
        'max_level':      5,
        'mana_cost':      20,
        'cooldown':       4,
        'type':           'debuff',
        'scale_stat':     'intuition',
        'scale_mult':     0.8,
        'base_value':     25,
        'duration':       3,
        'level_bonus':    0.08,
    },
    'steady_aim': {
        'id':             'steady_aim',
        'name':           '🧭 Твёрдый прицел',
        'description':    'Подготовка снайпера: создаёт короткое focus-окно для следующего commit-выстрела.',
        'weapon_id':      'short_bow',
        'branch':         'A',
        'unlock_mastery': 5,
        'max_level':      5,
        'mana_cost':      18,
        'cooldown':       4,
        'type':           'buff',
        'scale_stat':     'intuition',
        'scale_mult':     0.4,
        'base_value':     1,
        'duration':       1,
        'setup_duration': 2,
        'setup_accuracy_bonus': 30,
        'level_bonus':    0.05,
    },
    'piercing_arrow': {
        'id':             'piercing_arrow',
        'name':           '🏹 Пробивающая стрела',
        'description':    'Сильный payoff-выстрел с частичным игнором защиты: сильнее по отмеченной или бронированной цели.',
        'weapon_id':      'short_bow',
        'branch':         'A',
        'unlock_mastery': 7,
        'max_level':      5,
        'mana_cost':      30,
        'cooldown':       4,
        'type':           'damage',
        'scale_stat':     'intuition',
        'scale_mult':     2.2,
        'base_value':     220,
        'level_bonus':    0.12,
        'ignore_defense': 0.45,
        'armor_defense_threshold': 15,
        'marked_mult': 1.22,
        'armored_mult': 1.16,
        'marked_armored_mult': 1.30,
        'steady_mult': 1.08,
        'steady_payoff_mult': 1.35,
        'steady_accuracy_bonus': 20,
    },
    'deadeye': {
        'id':             'deadeye',
        'name':           '💀 Мёртвый глаз',
        'description':    'Капстоун Sniper: commit-выстрел с гарантированным попаданием, максимальный payoff по отмеченной цели.',
        'weapon_id':      'short_bow',
        'branch':         'A',
        'unlock_mastery': 10,
        'max_level':      5,
        'mana_cost':      44,
        'cooldown':       6,
        'type':           'damage',
        'scale_stat':     'intuition',
        'scale_mult':     2.7,
        'base_value':     290,
        'level_bonus':    0.14,
        'ignore_defense': 0.55,
        'marked_mult':    1.38,
        'steady_mult':    1.18,
        'marked_steady_mult': 1.55,
    },
    'eagle_eye': {
        'id':             'eagle_eye',
        'name':           '🦅 Орлиный глаз',
        'description':    'Следующие 3 атаки — гарантированный крит.',
        'weapon_id':      'short_bow',
        'branch':         'A',
        'unlock_mastery': 6,
        'max_level':      5,
        'mana_cost':      35,
        'cooldown':       5,
        'type':           'buff',
        'scale_stat':     'intuition',
        'scale_mult':     1.0,
        'base_value':     3,
        'duration':       3,
        'level_bonus':    0.2,
    },
    'bow_ult_a': {
        'id':             'bow_ult_a',
        'name':           '☄️ Пронзающая стрела',
        'description':    'Стрела пронзает все защиты. Урон x4, игнорирует 100% защиты.',
        'weapon_id':      'short_bow',
        'branch':         'A',
        'unlock_mastery': 10,
        'max_level':      5,
        'mana_cost':      60,
        'cooldown':       7,
        'type':           'damage',
        'scale_stat':     'intuition',
        'scale_mult':     3.5,
        'base_value':     350,
        'level_bonus':    0.15,
        'ignore_defense': 1.0,
    },

    # Ветка B — Ranger
    'quick_shot': {
        'id':             'quick_shot',
        'name':           '⚡ Быстрый выстрел',
        'description':    'Быстрая дешёвая атака для постоянного давления.',
        'weapon_id':      'short_bow',
        'branch':         'B',
        'unlock_mastery': 1,
        'max_level':      5,
        'mana_cost':      10,
        'cooldown':       1,
        'type':           'damage',
        'scale_stat':     'agility',
        'scale_mult':     1.2,
        'base_value':     110,
        'level_bonus':    0.08,
    },
    'hamstring_arrow': {
        'id':             'hamstring_arrow',
        'name':           '🪢 Подрезающая стрела',
        'description':    'Наносит урон и замедляет цель: базовый setup для ranger-tempo навыков.',
        'weapon_id':      'short_bow',
        'branch':         'B',
        'unlock_mastery': 3,
        'max_level':      5,
        'mana_cost':      16,
        'cooldown':       3,
        'type':           'damage',
        'scale_stat':     'agility',
        'scale_mult':     1.4,
        'base_value':     125,
        'slow_duration':  2,
        'level_bonus':    0.10,
    },
    'reposition': {
        'id':             'reposition',
        'name':           '↩️ Репозиция',
        'description':    'Тактический шаг назад: даёт короткое окно уклонения на 1 ответный удар.',
        'weapon_id':      'short_bow',
        'branch':         'B',
        'unlock_mastery': 5,
        'max_level':      5,
        'mana_cost':      18,
        'cooldown':       4,
        'type':           'buff',
        'scale_stat':     'agility',
        'scale_mult':     0.7,
        'base_value':     45,
        'duration':       1,
        'level_bonus':    0.08,
    },
    'volley_step': {
        'id':             'volley_step',
        'name':           '🏃‍➡️ Шаг залпа',
        'description':    'Мобильная серия из 2 попаданий: сильнее по замедленной цели, с небольшим бонусом в evasive-окно.',
        'weapon_id':      'short_bow',
        'branch':         'B',
        'unlock_mastery': 7,
        'max_level':      5,
        'mana_cost':      24,
        'cooldown':       4,
        'type':           'damage',
        'scale_stat':     'agility',
        'scale_mult':     1.7,
        'base_value':     70,
        'level_bonus':    0.11,
        'hits':           2,
        'slowed_mult':    1.15,
        'evasive_mult':   1.08,
        'slowed_evasive_mult': 1.24,
    },
    'rain_of_barbs': {
        'id':             'rain_of_barbs',
        'name':           '🌵 Ливень шипов',
        'description':    'Капстоун Ranger: шквал стрел для tempo-pressure. Сильнее по замедленной цели.',
        'weapon_id':      'short_bow',
        'branch':         'B',
        'unlock_mastery': 10,
        'max_level':      5,
        'mana_cost':      34,
        'cooldown':       6,
        'type':           'damage',
        'scale_stat':     'agility',
        'scale_mult':     2.0,
        'base_value':     75,
        'level_bonus':    0.11,
        'hits':           3,
        'slowed_mult':    1.22,
    },
    'retreat': {
        'id':             'retreat',
        'name':           '🏃 Отступление',
        'description':    'Отпрыгивает назад. +60% уклонения на 1 ход, атакует издали.',
        'weapon_id':      'short_bow',
        'branch':         'B',
        'unlock_mastery': 1,
        'max_level':      5,
        'mana_cost':      15,
        'cooldown':       3,
        'type':           'buff',
        'scale_stat':     'agility',
        'scale_mult':     0.8,
        'base_value':     60,
        'duration':       1,
        'level_bonus':    0.08,
    },
    'arrow_rain': {
        'id':             'arrow_rain',
        'name':           '🌧️ Дождь стрел',
        'description':    'Выпускает 5 стрел. Каждая наносит 40% урона.',
        'weapon_id':      'short_bow',
        'branch':         'B',
        'unlock_mastery': 3,
        'max_level':      5,
        'mana_cost':      30,
        'cooldown':       4,
        'type':           'damage',
        'scale_stat':     'intuition',
        'scale_mult':     1.5,
        'base_value':     40,
        'level_bonus':    0.1,
        'hits':           5,
    },
    'kite': {
        'id':             'kite',
        'name':           '🎪 Заманивание',
        'description':    'Замедляет врага. Он пропускает следующий ход.',
        'weapon_id':      'short_bow',
        'branch':         'B',
        'unlock_mastery': 6,
        'max_level':      5,
        'mana_cost':      25,
        'cooldown':       5,
        'type':           'control',
        'scale_stat':     'agility',
        'scale_mult':     0.5,
        'base_value':     1,
        'level_bonus':    0.2,
    },
    'bow_ult_b': {
        'id':             'bow_ult_b',
        'name':           '🌪️ Торнадо стрел',
        'description':    'Создаёт вихрь стрел. 8 ударов по 35% урона, шанс оглушения.',
        'weapon_id':      'short_bow',
        'branch':         'B',
        'unlock_mastery': 10,
        'max_level':      5,
        'mana_cost':      65,
        'cooldown':       8,
        'type':           'damage',
        'scale_stat':     'intuition',
        'scale_mult':     2.0,
        'base_value':     35,
        'level_bonus':    0.1,
        'hits':           8,
        'effect':         ('stun', 0.3, 1),
    },

    # ════════════════════════════════════════
    # ⚔️ ДВУРУЧНЫЙ МЕЧ
    # ════════════════════════════════════════

    # Ветка A — Executioner
    'heavy_swing': {
        'id':             'heavy_swing',
        'name':           '🪓 Тяжёлый взмах',
        'description':    'Базовый тяжёлый удар двуручным мечом.',
        'weapon_id':      'sword_2h',
        'branch':         'A',
        'unlock_mastery': 1,
        'max_level':      5,
        'mana_cost':      18,
        'cooldown':       3,
        'type':           'damage',
        'scale_stat':     'strength',
        'scale_mult':     1.8,
        'base_value':     148,
        'level_bonus':    0.10,
    },
    'armor_split': {
        'id':             'armor_split',
        'name':           '🧱 Раскол лат',
        'description':    'Подготавливает цель: создаёт короткое окно уязвимости.',
        'weapon_id':      'sword_2h',
        'branch':         'A',
        'unlock_mastery': 3,
        'max_level':      5,
        'mana_cost':      16,
        'cooldown':       3,
        'type':           'debuff',
        'scale_stat':     'strength',
        'scale_mult':     0.45,
        'base_value':     18,
        'duration':       2,
        'level_bonus':    0.07,
    },
    'executioners_focus': {
        'id':             'executioners_focus',
        'name':           '🎯 Фокус палача',
        'description':    'Короткий setup-бафф: усиливает следующий тяжёлый payoff-удар.',
        'weapon_id':      'sword_2h',
        'branch':         'A',
        'unlock_mastery': 5,
        'max_level':      5,
        'mana_cost':      20,
        'cooldown':       4,
        'type':           'buff',
        'scale_stat':     'strength',
        'scale_mult':     0.6,
        'base_value':     18,
        'duration':       2,
        'level_bonus':    0.08,
    },
    'cleave_through': {
        'id':             'cleave_through',
        'name':           '🗡️ Рассечение насквозь',
        'description':    'Payoff-удар: сильнее в окно уязвимости, по раненой цели и под Фокусом палача.',
        'weapon_id':      'sword_2h',
        'branch':         'A',
        'unlock_mastery': 7,
        'max_level':      5,
        'mana_cost':      28,
        'cooldown':       4,
        'type':           'damage',
        'scale_stat':     'strength',
        'scale_mult':     2.1,
        'base_value':     172,
        'level_bonus':    0.11,
    },
    'executioners_stroke': {
        'id':             'executioners_stroke',
        'name':           '⚔️ Удар палача',
        'description':    'Капстоун Executioner: тяжёлый добивающий удар, сильнее по раненой цели.',
        'weapon_id':      'sword_2h',
        'branch':         'A',
        'unlock_mastery': 10,
        'max_level':      5,
        'mana_cost':      42,
        'cooldown':       6,
        'type':           'damage',
        'scale_stat':     'strength',
        'scale_mult':     2.6,
        'base_value':     205,
        'level_bonus':    0.12,
    },

    # Ветка B — Blademaster
    'battle_stance': {
        'id':             'battle_stance',
        'name':           '⚔️ Боевая стойка',
        'description':    'Темповая стойка: короткое offensive-окно для техничных разменов.',
        'weapon_id':      'sword_2h',
        'branch':         'B',
        'unlock_mastery': 1,
        'max_level':      5,
        'mana_cost':      16,
        'cooldown':       3,
        'type':           'buff',
        'scale_stat':     'agility',
        'scale_mult':     0.6,
        'base_value':     16,
        'duration':       2,
        'level_bonus':    0.08,
    },
    'twin_cut': {
        'id':             'twin_cut',
        'name':           '✂️ Двойной срез',
        'description':    'Базовая техничная серия из двух ударов.',
        'weapon_id':      'sword_2h',
        'branch':         'B',
        'unlock_mastery': 3,
        'max_level':      5,
        'mana_cost':      20,
        'cooldown':       3,
        'type':           'damage',
        'scale_stat':     'agility',
        'scale_mult':     1.6,
        'base_value':     78,
        'level_bonus':    0.10,
        'hits':           2,
    },
    'riposte_step': {
        'id':             'riposte_step',
        'name':           '👣 Шаг рипоста',
        'description':    'Защитный тайминг и репозиция: даёт короткое окно уклонения.',
        'weapon_id':      'sword_2h',
        'branch':         'B',
        'unlock_mastery': 5,
        'max_level':      5,
        'mana_cost':      18,
        'cooldown':       4,
        'type':           'buff',
        'scale_stat':     'agility',
        'scale_mult':     0.5,
        'base_value':     40,
        'duration':       2,
        'level_bonus':    0.08,
    },
    'flowing_combo': {
        'id':             'flowing_combo',
        'name':           '🌊 Текучая комбинация',
        'description':    'Payoff-удар Blademaster: сильнее в окно Боевой стойки и расходует её.',
        'weapon_id':      'sword_2h',
        'branch':         'B',
        'unlock_mastery': 7,
        'max_level':      5,
        'mana_cost':      28,
        'cooldown':       4,
        'type':           'damage',
        'scale_stat':     'agility',
        'scale_mult':     2.0,
        'base_value':     162,
        'level_bonus':    0.11,
    },
    'masters_sequence': {
        'id':             'masters_sequence',
        'name':           '🌀 Последовательность мастера',
        'description':    'Капстоун Blademaster: техничный финишер из нескольких ударов, сильнее в стойке.',
        'weapon_id':      'sword_2h',
        'branch':         'B',
        'unlock_mastery': 10,
        'max_level':      5,
        'mana_cost':      38,
        'cooldown':       6,
        'type':           'damage',
        'scale_stat':     'agility',
        'scale_mult':     2.2,
        'base_value':     72,
        'level_bonus':    0.11,
        'hits':           3,
    },

    # ════════════════════════════════════════
    # 🪓 ДВУРУЧНЫЙ ТОПОР
    # ════════════════════════════════════════

    # Ветка A — Berserker
    'rage_call': {
        'id':             'rage_call',
        'name':           '😤 Зов ярости',
        'description':    'Рискованный self-buff: усиливает урон в ярости ценой части HP. Нельзя умереть от цены навыка.',
        'weapon_id':      'axe_2h',
        'branch':         'A',
        'unlock_mastery': 1,
        'max_level':      5,
        'mana_cost':      16,
        'cooldown':       4,
        'type':           'buff',
        'scale_stat':     'strength',
        'scale_mult':     0.55,
        'base_value':     14,
        'duration':       2,
        'defense_penalty': 25,
        'hp_cost_ratio':  0.12,
        'level_bonus':    0.08,
    },
    'savage_chop': {
        'id':             'savage_chop',
        'name':           '🪓 Свирепый удар',
        'description':    'Базовый тяжёлый удар ветки берсерка.',
        'weapon_id':      'axe_2h',
        'branch':         'A',
        'unlock_mastery': 3,
        'max_level':      5,
        'mana_cost':      20,
        'cooldown':       3,
        'type':           'damage',
        'scale_stat':     'strength',
        'scale_mult':     1.8,
        'base_value':     150,
        'level_bonus':    0.11,
    },
    'blooded_resolve': {
        'id':             'blooded_resolve',
        'name':           '🩸 Кровавая решимость',
        'description':    'Умеренное самоисцеление. Чем ниже HP, тем сильнее лечение.',
        'weapon_id':      'axe_2h',
        'branch':         'A',
        'unlock_mastery': 5,
        'max_level':      5,
        'mana_cost':      20,
        'cooldown':       4,
        'type':           'heal',
        'scale_stat':     'vitality',
        'scale_mult':     1.0,
        'base_value':     24,
        'level_bonus':    0.08,
    },
    'frenzy_chain': {
        'id':             'frenzy_chain',
        'name':           '⛓️ Цепь безумия',
        'description':    'Серия из 2 ударов. В ярости получает заметный бонус и расходует её.',
        'weapon_id':      'axe_2h',
        'branch':         'A',
        'unlock_mastery': 7,
        'max_level':      5,
        'mana_cost':      28,
        'cooldown':       4,
        'type':           'damage',
        'scale_stat':     'strength',
        'scale_mult':     1.9,
        'base_value':     88,
        'level_bonus':    0.10,
        'hits':           2,
    },
    'last_roar': {
        'id':             'last_roar',
        'name':           '🗯️ Последний рык',
        'description':    'Тяжёлый добивающий удар. Сильнее в ярости и при низком HP.',
        'weapon_id':      'axe_2h',
        'branch':         'A',
        'unlock_mastery': 10,
        'max_level':      5,
        'mana_cost':      40,
        'cooldown':       6,
        'type':           'damage',
        'scale_stat':     'strength',
        'scale_mult':     2.4,
        'base_value':     195,
        'level_bonus':    0.12,
    },

    # Ветка B — Ravager
    'bleeding_cut': {
        'id':             'bleeding_cut',
        'name':           '🩸 Кровоточащий разрез',
        'description':    'Наносит урон и накладывает bleed на цель.',
        'weapon_id':      'axe_2h',
        'branch':         'B',
        'unlock_mastery': 1,
        'max_level':      5,
        'mana_cost':      18,
        'cooldown':       3,
        'type':           'damage',
        'scale_stat':     'strength',
        'scale_mult':     1.6,
        'base_value':     130,
        'level_bonus':    0.10,
    },
    'sunder_armor': {
        'id':             'sunder_armor',
        'name':           '🧱 Раскол брони',
        'description':    'Вскрывает защиту цели: повышает входящий по ней урон на короткое окно.',
        'weapon_id':      'axe_2h',
        'branch':         'B',
        'unlock_mastery': 3,
        'max_level':      5,
        'mana_cost':      18,
        'cooldown':       3,
        'type':           'debuff',
        'scale_stat':     'strength',
        'scale_mult':     0.45,
        'base_value':     18,
        'duration':       2,
        'level_bonus':    0.07,
    },
    'brutal_overhead': {
        'id':             'brutal_overhead',
        'name':           '🔨 Жестокий навес',
        'description':    'Тяжёлый anti-armor удар с частичным игнором защиты.',
        'weapon_id':      'axe_2h',
        'branch':         'B',
        'unlock_mastery': 5,
        'max_level':      5,
        'mana_cost':      26,
        'cooldown':       4,
        'type':           'damage',
        'scale_stat':     'strength',
        'scale_mult':     2.0,
        'base_value':     165,
        'level_bonus':    0.11,
        'ignore_defense': 0.35,
    },
    'reopen_wounds': {
        'id':             'reopen_wounds',
        'name':           '🔪 Вскрыть раны',
        'description':    'Payoff-удар: сильнее по кровоточащей и/или вскрытой цели.',
        'weapon_id':      'axe_2h',
        'branch':         'B',
        'unlock_mastery': 7,
        'max_level':      5,
        'mana_cost':      30,
        'cooldown':       4,
        'type':           'damage',
        'scale_stat':     'strength',
        'scale_mult':     2.0,
        'base_value':     170,
        'level_bonus':    0.11,
    },
    'ravage': {
        'id':             'ravage',
        'name':           '💥 Разорение',
        'description':    'Капстоун Ravager: тяжёлый punish-удар, сильнее в подготовленное окно.',
        'weapon_id':      'axe_2h',
        'branch':         'B',
        'unlock_mastery': 10,
        'max_level':      5,
        'mana_cost':      44,
        'cooldown':       6,
        'type':           'damage',
        'scale_stat':     'strength',
        'scale_mult':     2.5,
        'base_value':     205,
        'level_bonus':    0.12,
    },
    # Legacy compatibility entry: old berserker-style runtime hook.
    'berserker': {
        'id':             'berserker',
        'name':           '😤 Берсерк',
        'description':    'Повышает урон на несколько ходов ценой выживаемости.',
        'weapon_id':      'axe_2h',
        'branch':         'A',
        'unlock_mastery': 1,
        'max_level':      5,
        'mana_cost':      20,
        'cooldown':       4,
        'type':           'buff',
        'scale_stat':     'strength',
        'scale_mult':     0.6,
        'base_value':     20,
        'duration':       3,
        'defense_penalty': 25,
        'level_bonus':    0.08,
    },

    # ════════════════════════════════════════
    # 🔮 МАГИЧЕСКИЙ ПОСОХ
    # ════════════════════════════════════════

    # Ветка A — Огонь
    'fireball': {
        'id':             'fireball',
        'name':           '🔥 Огненный шар',
        'description':    'Запускает огненный шар. Может поджечь цель.',
        'weapon_id':      'magic_staff',
        'branch':         'A',
        'unlock_mastery': 1,
        'max_level':      5,
        'mana_cost':      20,
        'cooldown':       2,
        'type':           'damage',
        'scale_stat':     'intuition',
        'scale_mult':     2.0,
        'base_value':     140,
        'level_bonus':    0.15,
        'effect':         ('burn', 0.30, 2),
    },
    'arcane_surge': {
        'id':             'arcane_surge',
        'name':           '✨ Тайный всплеск',
        'description':    'Короткое setup-окно ветки Разрушения: усиливает следующий крупный destructive-каст (в первую очередь Тайное копьё, а также Катаклизм).',
        'weapon_id':      'magic_staff',
        'branch':         'A',
        'unlock_mastery': 3,
        'max_level':      5,
        'mana_cost':      18,
        'cooldown':       3,
        'type':           'buff',
        'scale_stat':     'intuition',
        'scale_mult':     0.7,
        'base_value':     28,
        'duration':       2,
        'setup_runtime_turns': 2,
        'level_bonus':    0.08,
    },
    'flame_wave': {
        'id':             'flame_wave',
        'name':           '🔥 Волна пламени',
        'description':    'Серия огненных ударов для стабильного давления.',
        'weapon_id':      'magic_staff',
        'branch':         'A',
        'unlock_mastery': 5,
        'max_level':      5,
        'mana_cost':      28,
        'cooldown':       4,
        'type':           'damage',
        'scale_stat':     'intuition',
        'scale_mult':     2.1,
        'base_value':     72,
        'level_bonus':    0.11,
        'hits':           2,
    },
    'arcane_lance': {
        'id':             'arcane_lance',
        'name':           '💠 Тайное копьё',
        'description':    'Сильный выстрел энергией, особенно опасный в окно Тайного всплеска.',
        'weapon_id':      'magic_staff',
        'branch':         'A',
        'unlock_mastery': 7,
        'max_level':      5,
        'mana_cost':      30,
        'cooldown':       4,
        'type':           'damage',
        'scale_stat':     'intuition',
        'scale_mult':     2.6,
        'base_value':     170,
        'level_bonus':    0.12,
        'surge_payoff_scale': 1.0,
        'surge_payoff_cap_percent': 55,
    },
    'cataclysm': {
        'id':             'cataclysm',
        'name':           '🌋 Катаклизм',
        'description':    'Капстоун Разрушения: тяжёлый огненный каст, сильнее в окно Тайного всплеска и/или по горящей цели.',
        'weapon_id':      'magic_staff',
        'branch':         'A',
        'unlock_mastery': 10,
        'max_level':      5,
        'mana_cost':      48,
        'cooldown':       6,
        'type':           'damage',
        'scale_stat':     'intuition',
        'scale_mult':     3.3,
        'base_value':     225,
        'level_bonus':    0.13,
        'effect':         ('burn', 0.45, 2),
        'surge_payoff_mult': 1.22,
        'burn_payoff_mult': 1.18,
        'surge_burn_payoff_mult': 1.32,
    },
    'burning_ground': {
        'id':             'burning_ground',
        'name':           '🌋 Горящая земля',
        'description':    'Поджигает землю под врагом. 25% урона в ход на 3 хода.',
        'weapon_id':      'magic_staff',
        'branch':         'A',
        'unlock_mastery': 3,
        'max_level':      5,
        'mana_cost':      25,
        'cooldown':       4,
        'type':           'debuff',
        'scale_stat':     'intuition',
        'scale_mult':     1.5,
        'base_value':     25,
        'level_bonus':    0.15,
        'effect':         ('burn', 1.0, 3),
    },
    'fire_shield': {
        'id':             'fire_shield',
        'name':           '🔆 Огненный щит',
        'description':    'Окружает огнём. Атакующий получает 30% твоего урона в ответ.',
        'weapon_id':      'magic_staff',
        'branch':         'A',
        'unlock_mastery': 6,
        'max_level':      5,
        'mana_cost':      30,
        'cooldown':       4,
        'type':           'buff',
        'scale_stat':     'intuition',
        'scale_mult':     1.2,
        'base_value':     30,
        'duration':       3,
        'level_bonus':    0.15,
    },
    'meteor': {
        'id':             'meteor',
        'name':           '☄️ Метеор',
        'description':    'Призывает метеор. Огромный урон + поджигает + оглушает.',
        'weapon_id':      'magic_staff',
        'branch':         'A',
        'unlock_mastery': 10,
        'max_level':      5,
        'mana_cost':      70,
        'cooldown':       7,
        'type':           'damage',
        'scale_stat':     'intuition',
        'scale_mult':     4.0,
        'base_value':     320,
        'level_bonus':    0.15,
        'effect':         ('stun', 0.5, 2),
    },

    # Ветка B — Лёд
    'ice_lance': {
        'id':             'ice_lance',
        'name':           '❄️ Ледяное копьё',
        'description':    'Пронзает врага льдом. Замедляет на 1 ход.',
        'weapon_id':      'magic_staff',
        'branch':         'B',
        'unlock_mastery': 1,
        'max_level':      5,
        'mana_cost':      20,
        'cooldown':       2,
        'type':           'damage',
        'scale_stat':     'intuition',
        'scale_mult':     1.8,
        'base_value':     130,
        'level_bonus':    0.12,
        'effect':         ('slow', 0.5, 1),
    },
    'ice_chains': {
        'id':             'ice_chains',
        'name':           '⛓️ Ледяные цепи',
        'description':    'Сковывает врага льдом. Пропускает ход.',
        'weapon_id':      'magic_staff',
        'branch':         'B',
        'unlock_mastery': 3,
        'max_level':      5,
        'mana_cost':      30,
        'cooldown':       4,
        'type':           'control',
        'scale_stat':     'intuition',
        'scale_mult':     0.5,
        'base_value':     1,
        'level_bonus':    0.2,
        'effect':         ('freeze', 0.8, 3),
    },
    'blizzard': {
        'id':             'blizzard',
        'name':           '🌨️ Метель',
        'description':    'Вызывает метель. Снижает точность врага на 40% на 3 хода.',
        'weapon_id':      'magic_staff',
        'branch':         'B',
        'unlock_mastery': 6,
        'max_level':      5,
        'mana_cost':      35,
        'cooldown':       5,
        'type':           'debuff',
        'scale_stat':     'intuition',
        'scale_mult':     1.0,
        'base_value':     40,
        'level_bonus':    0.08,
    },
    'absolute_zero': {
        'id':             'absolute_zero',
        'name':           '🧊 Абсолютный ноль',
        'description':    'Ледяной капстоун: наносит тяжёлый урон и сильнее бьёт по замедленной или замороженной цели.',
        'weapon_id':      'magic_staff',
        'branch':         'B',
        'unlock_mastery': 10,
        'max_level':      5,
        'mana_cost':      52,
        'cooldown':       7,
        'type':           'damage',
        'scale_stat':     'intuition',
        'scale_mult':     3.0,
        'base_value':     205,
        'level_bonus':    0.12,
        'effect':         ('freeze', 0.45, 1),
        'slow_payoff_mult': 1.18,
        'freeze_payoff_mult': 1.25,
        'controlled_payoff_mult': 1.30,
    },
    'frost_bolt': {
        'id':             'frost_bolt',
        'name':           '❄️ Ледяной болт',
        'description':    'Базовый контроль ветки: наносит урон и замедляет цель.',
        'weapon_id':      'magic_staff',
        'branch':         'B',
        'unlock_mastery': 1,
        'max_level':      5,
        'mana_cost':      18,
        'cooldown':       2,
        'type':           'damage',
        'scale_stat':     'intuition',
        'scale_mult':     1.9,
        'base_value':     125,
        'level_bonus':    0.11,
        'effect':         ('slow', 1.0, 2),
    },
    'ice_shackles': {
        'id':             'ice_shackles',
        'name':           '⛓️ Ледяные оковы',
        'description':    'Усиливает контроль: коротко замораживает цель.',
        'weapon_id':      'magic_staff',
        'branch':         'B',
        'unlock_mastery': 3,
        'max_level':      5,
        'mana_cost':      24,
        'cooldown':       4,
        'type':           'control',
        'scale_stat':     'intuition',
        'scale_mult':     0.8,
        'base_value':     1,
        'level_bonus':    0.1,
        'effect':         ('freeze', 1.0, 1),
    },
    'mana_shield': {
        'id':             'mana_shield',
        'name':           '🛡️ Щит маны',
        'description':    'Защитная утилита: повышает защиту на короткое окно.',
        'weapon_id':      'magic_staff',
        'branch':         'B',
        'unlock_mastery': 5,
        'max_level':      5,
        'mana_cost':      22,
        'cooldown':       4,
        'type':           'buff',
        'scale_stat':     'intuition',
        'scale_mult':     0.75,
        'base_value':     22,
        'duration':       2,
        'level_bonus':    0.08,
    },
    'shatter': {
        'id':             'shatter',
        'name':           '💥 Осколочный удар',
        'description':    'Payoff-кнопка контроля: заметно сильнее по замедленной или замороженной цели.',
        'weapon_id':      'magic_staff',
        'branch':         'B',
        'unlock_mastery': 7,
        'max_level':      5,
        'mana_cost':      30,
        'cooldown':       4,
        'type':           'damage',
        'scale_stat':     'intuition',
        'scale_mult':     2.5,
        'base_value':     160,
        'level_bonus':    0.12,
        'slow_payoff_mult': 1.25,
        'freeze_payoff_mult': 1.35,
        'controlled_payoff_mult': 1.45,
    },

    # ════════════════════════════════════════
    # 🪄 ВОЛШЕБНАЯ ПАЛОЧКА
    # ════════════════════════════════════════

    # Ветка A — Arcanist
    'arcane_bolt': {
        'id':             'arcane_bolt',
        'name':           '✨ Тайный болт',
        'description':    'Быстрый магический выстрел для темпового давления.',
        'weapon_id':      'wand',
        'branch':         'A',
        'unlock_mastery': 1,
        'max_level':      5,
        'mana_cost':      16,
        'cooldown':       2,
        'type':           'damage',
        'scale_stat':     'intuition',
        'scale_mult':     1.9,
        'base_value':     120,
        'level_bonus':    0.10,
    },
    'spell_echo': {
        'id':             'spell_echo',
        'name':           '🔁 Эхо заклинаний',
        'description':    'Усиливает следующее атакующее заклинание палочки. Максимально раскрывается в цепочке Arcanist.',
        'weapon_id':      'wand',
        'branch':         'A',
        'unlock_mastery': 3,
        'max_level':      5,
        'mana_cost':      18,
        'cooldown':       3,
        'type':           'buff',
        'scale_stat':     'intuition',
        'scale_mult':     0.7,
        'base_value':     18,
        'duration':       1,
        'level_bonus':    0.08,
    },
    'quick_channel': {
        'id':             'quick_channel',
        'name':           '⚡ Быстрый канал',
        'description':    'Возвращает немного маны и усиливает следующее атакующее заклинание палочки. Лучше всего работает в темповой серии Arcanist.',
        'weapon_id':      'wand',
        'branch':         'A',
        'unlock_mastery': 5,
        'max_level':      5,
        'mana_cost':      20,
        'cooldown':       4,
        'type':           'buff',
        'scale_stat':     'intuition',
        'scale_mult':     0.6,
        'base_value':     14,
        'duration':       1,
        'level_bonus':    0.08,
    },
    'overload': {
        'id':             'overload',
        'name':           '💥 Перегрузка',
        'description':    'Мощный payoff-выстрел, который становится сильнее с Эхом и Быстрым каналом.',
        'weapon_id':      'wand',
        'branch':         'A',
        'unlock_mastery': 7,
        'max_level':      5,
        'mana_cost':      30,
        'cooldown':       5,
        'type':           'damage',
        'scale_stat':     'intuition',
        'scale_mult':     2.4,
        'base_value':     168,
        'level_bonus':    0.11,
    },
    'arcane_barrage': {
        'id':             'arcane_barrage',
        'name':           '🌠 Тайный залп',
        'description':    'Быстрая серия магических попаданий; сильнее под подготовкой Arcanist.',
        'weapon_id':      'wand',
        'branch':         'A',
        'unlock_mastery': 10,
        'max_level':      5,
        'mana_cost':      36,
        'cooldown':       6,
        'type':           'damage',
        'scale_stat':     'intuition',
        'scale_mult':     2.6,
        'base_value':     90,
        'level_bonus':    0.10,
        'hits':           3,
    },

    # Ветка B — Duelist
    'dueling_ward': {
        'id':             'dueling_ward',
        'name':           '🛡️ Дуэльный покров',
        'description':    'Создаёт защитное окно для дуэли, снижая входящий урон.',
        'weapon_id':      'wand',
        'branch':         'B',
        'unlock_mastery': 1,
        'max_level':      5,
        'mana_cost':      18,
        'cooldown':       3,
        'type':           'buff',
        'scale_stat':     'intuition',
        'scale_mult':     0.7,
        'base_value':     20,
        'duration':       2,
        'level_bonus':    0.08,
    },
    'hex_bolt': {
        'id':             'hex_bolt',
        'name':           '🌀 Проклятый болт',
        'description':    'Надёжный магический удар для дуэльного давления.',
        'weapon_id':      'wand',
        'branch':         'B',
        'unlock_mastery': 3,
        'max_level':      5,
        'mana_cost':      18,
        'cooldown':       2,
        'type':           'damage',
        'scale_stat':     'intuition',
        'scale_mult':     2.0,
        'base_value':     126,
        'level_bonus':    0.10,
    },
    'mana_feint': {
        'id':             'mana_feint',
        'name':           '🎭 Маневр маны',
        'description':    'Хитрый каст: наносит урон и замедляет цель.',
        'weapon_id':      'wand',
        'branch':         'B',
        'unlock_mastery': 5,
        'max_level':      5,
        'mana_cost':      20,
        'cooldown':       3,
        'type':           'debuff',
        'scale_stat':     'intuition',
        'scale_mult':     0.8,
        'base_value':     105,
        'level_bonus':    0.08,
        'effect':         ('slow', 1.0, 2),
    },
    'counterpulse': {
        'id':             'counterpulse',
        'name':           '🫧 Контр-импульс',
        'description':    'Карательный выстрел: сильнее с Дуэльным покровом и по замедленной цели.',
        'weapon_id':      'wand',
        'branch':         'B',
        'unlock_mastery': 7,
        'max_level':      5,
        'mana_cost':      28,
        'cooldown':       4,
        'type':           'damage',
        'scale_stat':     'intuition',
        'scale_mult':     2.4,
        'base_value':     160,
        'level_bonus':    0.11,
    },
    'duel_arc': {
        'id':             'duel_arc',
        'name':           '⚜️ Дуэльная дуга',
        'description':    'Капстоун-удар Duelist: особенно опасен в дуэльном окне и по замедленной цели.',
        'weapon_id':      'wand',
        'branch':         'B',
        'unlock_mastery': 10,
        'max_level':      5,
        'mana_cost':      34,
        'cooldown':       6,
        'type':           'damage',
        'scale_stat':     'intuition',
        'scale_mult':     2.7,
        'base_value':     178,
        'level_bonus':    0.12,
    },

    # ════════════════════════════════════════
    # ✨ СВЯТОЙ ПОСОХ
    # ════════════════════════════════════════

    # Ветка A — Свет (legacy, kept for compatibility rows in DB)
    'holy_bolt': {
        'id':             'holy_bolt',
        'name':           '✨ Световой заряд',
        'description':    'Заряд света. Особенно эффективен против нежити.',
        'weapon_id':      'holy_staff',
        'branch':         'A',
        'unlock_mastery': 1,
        'max_level':      5,
        'mana_cost':      18,
        'cooldown':       2,
        'type':           'damage',
        'scale_stat':     'wisdom',
        'scale_mult':     2.0,
        'base_value':     130,
        'level_bonus':    0.15,
    },
    'smite': {
        'id':             'smite',
        'name':           '⚡ Кара небес',
        'description':    'Точный удар светом. Надёжный атакующий спелл ветки Света.',
        'weapon_id':      'holy_staff',
        'branch':         'B',
        'unlock_mastery': 1,
        'max_level':      5,
        'mana_cost':      24,
        'cooldown':       3,
        'type':           'damage',
        'scale_stat':     'wisdom',
        'scale_mult':     2.1,
        'base_value':     140,
        'level_bonus':    0.12,
        'damage_school':  'holy',
    },
    'consecration': {
        'id':             'consecration',
        'name':           '🌟 Освящение',
        'description':    'Освящает землю. 20% урона светом в ход врагу на 3 хода.',
        'weapon_id':      'holy_staff',
        'branch':         'A',
        'unlock_mastery': 6,
        'max_level':      5,
        'mana_cost':      35,
        'cooldown':       5,
        'type':           'debuff',
        'scale_stat':     'wisdom',
        'scale_mult':     1.5,
        'base_value':     20,
        'level_bonus':    0.15,
        'effect':         ('burn', 1.0, 3),
    },
    'divine_wrath': {
        'id':             'divine_wrath',
        'name':           '☀️ Божественный гнев',
        'description':    'Ультимативный удар светом. Огромный урон, лечит тебя на 50% нанесённого.',
        'weapon_id':      'holy_staff',
        'branch':         'A',
        'unlock_mastery': 10,
        'max_level':      5,
        'mana_cost':      70,
        'cooldown':       7,
        'type':           'damage',
        'scale_stat':     'wisdom',
        'scale_mult':     4.0,
        'base_value':     300,
        'level_bonus':    0.15,
        'lifesteal':      0.5,
    },

    # Ветка A — Исцеление
    'heal': {
        'id':             'heal',
        'name':           '💚 Исцеление',
        'description':    'Восстанавливает HP. Сила лечения растёт с Мудростью.',
        'weapon_id':      'holy_staff',
        'branch':         'A',
        'unlock_mastery': 1,
        'max_level':      5,
        'mana_cost':      20,
        'cooldown':       2,
        'type':           'heal',
        'scale_stat':     'wisdom',
        'scale_mult':     3.0,
        'base_value':     44,
        'level_bonus':    0.20,
    },
    'blessing': {
        'id':             'blessing',
        'name':           '🙏 Благословение',
        'description':    'Поддерживающее благословение: повышает характеристики и усиливает устойчивость через темп.',
        'weapon_id':      'holy_staff',
        'branch':         'A',
        'unlock_mastery': 7,
        'max_level':      5,
        'mana_cost':      30,
        'cooldown':       5,
        'type':           'buff',
        'scale_stat':     'wisdom',
        'scale_mult':     0.5,
        'base_value':     20,
        'duration':       3,
        'level_bonus':    0.08,
    },
    'regeneration': {
        'id':             'regeneration',
        'name':           '♻️ Регенерация',
        'description':    'Накладывает длительное исцеление по ходам (HoT).',
        'weapon_id':      'holy_staff',
        'branch':         'A',
        'unlock_mastery': 3,
        'max_level':      5,
        'mana_cost':      35,
        'cooldown':       5,
        'type':           'buff',
        'scale_stat':     'wisdom',
        'scale_mult':     2.0,
        'base_value':     25,
        'duration':       4,
        'level_bonus':    0.15,
    },
    'resurrection': {
        'id':             'resurrection',
        'name':           '💫 Воскрешение',
        'description':    'Одноразовая holy-защита от смерти: при летальном уроне спасает и восстанавливает часть HP.',
        'weapon_id':      'holy_staff',
        'branch':         'A',
        'unlock_mastery': 10,
        'max_level':      5,
        'mana_cost':      80,
        'cooldown':       10,
        'type':           'buff',
        'scale_stat':     'wisdom',
        'scale_mult':     1.0,
        'base_value':     50,
        'duration':       5,
        'level_bonus':    0.1,
    },
    'cleanse': {
        'id':             'cleanse',
        'name':           '🕊️ Очищение',
        'description':    'Снимает поддерживаемые негативные эффекты и даёт умеренное восстановление HP.',
        'weapon_id':      'holy_staff',
        'branch':         'A',
        'unlock_mastery': 5,
        'max_level':      5,
        'mana_cost':      24,
        'cooldown':       4,
        'type':           'buff',
        'scale_stat':     'wisdom',
        'scale_mult':     1.2,
        'base_value':     24,
        'duration':       0,
        'level_bonus':    0.10,
        'cleanse_max_effects': 3,
        'cleanse_heal_ratio': 0.4,
    },
    'radiant_ward': {
        'id':             'radiant_ward',
        'name':           '🛡️ Сияющий покров',
        'description':    'Световой защитный покров на короткое окно.',
        'weapon_id':      'holy_staff',
        'branch':         'B',
        'unlock_mastery': 3,
        'max_level':      5,
        'mana_cost':      26,
        'cooldown':       4,
        'type':           'buff',
        'scale_stat':     'wisdom',
        'scale_mult':     0.6,
        'base_value':     16,
        'duration':       2,
        'level_bonus':    0.08,
    },
    'judgment_mark': {
        'id':             'judgment_mark',
        'name':           '🏷️ Печать суда',
        'description':    'Помечает цель святой меткой: усиливает payoff-удары ветки Света на время метки.',
        'weapon_id':      'holy_staff',
        'branch':         'B',
        'unlock_mastery': 5,
        'max_level':      5,
        'mana_cost':      22,
        'cooldown':       3,
        'type':           'debuff',
        'scale_stat':     'wisdom',
        'scale_mult':     0.6,
        'base_value':     18,
        'duration':       3,
        'level_bonus':    0.08,
    },
    'sanctified_burst': {
        'id':             'sanctified_burst',
        'name':           '✨ Освящённый всплеск',
        'description':    'Сильный удар светом. Заметно мощнее по помеченной цели.',
        'weapon_id':      'holy_staff',
        'branch':         'B',
        'unlock_mastery': 7,
        'max_level':      5,
        'mana_cost':      32,
        'cooldown':       4,
        'type':           'damage',
        'scale_stat':     'wisdom',
        'scale_mult':     2.8,
        'base_value':     180,
        'level_bonus':    0.12,
        'damage_school':  'holy',
        'judged_payoff_mult': 1.30,
        'judged_ward_payoff_mult': 1.38,
    },
    'halo_of_dawn': {
        'id':             'halo_of_dawn',
        'name':           '🌅 Ореол рассвета',
        'description':    'Капстоун Света: святой импульс с payoff по помеченной цели и умеренным самоисцелением.',
        'weapon_id':      'holy_staff',
        'branch':         'B',
        'unlock_mastery': 10,
        'max_level':      5,
        'mana_cost':      48,
        'cooldown':       6,
        'type':           'damage',
        'scale_stat':     'wisdom',
        'scale_mult':     3.2,
        'base_value':     210,
        'level_bonus':    0.13,
        'damage_school':  'holy',
        'judged_payoff_mult': 1.35,
        'judged_ward_payoff_mult': 1.45,
        'heal_from_damage_ratio': 0.12,
    },

    # ════════════════════════════════════════
    # ✨ СВЯЩЕННЫЙ ЖЕЗЛ
    # ════════════════════════════════════════
    'sacred_shield': {
        'id':             'sacred_shield',
        'name':           '🛡️ Священный щит',
        'description':    'Укрепляет тебя светом: снижает входящий урон на короткое окно.',
        'weapon_id':      'holy_rod',
        'branch':         'A',
        'unlock_mastery': 1,
        'max_level':      5,
        'mana_cost':      20,
        'cooldown':       3,
        'type':           'buff',
        'scale_stat':     'wisdom',
        'scale_mult':     0.5,
        'base_value':     16,
        'duration':       2,
        'level_bonus':    0.07,
    },
    'mend_self': {
        'id':             'mend_self',
        'name':           '💚 Самоисцеление',
        'description':    'Восстанавливает себе здоровье. Базовый self-heal ветки.',
        'weapon_id':      'holy_rod',
        'branch':         'A',
        'unlock_mastery': 3,
        'max_level':      5,
        'mana_cost':      22,
        'cooldown':       3,
        'type':           'heal',
        'scale_stat':     'wisdom',
        'scale_mult':     2.2,
        'base_value':     30,
        'level_bonus':    0.12,
    },
    'aura_of_resolve': {
        'id':             'aura_of_resolve',
        'name':           '✨ Аура решимости',
        'description':    'Короткий аурный бафф: умеренно усиливает характеристики на несколько ходов.',
        'weapon_id':      'holy_rod',
        'branch':         'A',
        'unlock_mastery': 5,
        'max_level':      5,
        'mana_cost':      24,
        'cooldown':       4,
        'type':           'buff',
        'scale_stat':     'wisdom',
        'scale_mult':     0.3,
        'base_value':     10,
        'duration':       2,
        'level_bonus':    0.06,
    },
    'aegis_strike': {
        'id':             'aegis_strike',
        'name':           '⚔️ Эгидный удар',
        'description':    'Holy-удар, заметно сильнее под активной защитой.',
        'weapon_id':      'holy_rod',
        'branch':         'A',
        'unlock_mastery': 7,
        'max_level':      5,
        'mana_cost':      26,
        'cooldown':       4,
        'type':           'damage',
        'scale_stat':     'wisdom',
        'scale_mult':     1.8,
        'base_value':     145,
        'level_bonus':    0.11,
        'damage_school':  'holy',
    },
    'guardian_light': {
        'id':             'guardian_light',
        'name':           '🌟 Свет хранителя',
        'description':    'Капстоун Protector: усиленный holy-удар в окно защиты, после удара обновляет короткий защитный бафф.',
        'weapon_id':      'holy_rod',
        'branch':         'A',
        'unlock_mastery': 10,
        'max_level':      5,
        'mana_cost':      36,
        'cooldown':       6,
        'type':           'damage',
        'scale_stat':     'wisdom',
        'scale_mult':     2.1,
        'base_value':     165,
        'level_bonus':    0.12,
        'damage_school':  'holy',
    },
    'judgment': {
        'id':             'judgment',
        'name':           '🏷️ Суд',
        'description':    'Помечает цель и повышает входящий по ней урон на короткое окно.',
        'weapon_id':      'holy_rod',
        'branch':         'B',
        'unlock_mastery': 1,
        'max_level':      5,
        'mana_cost':      20,
        'cooldown':       3,
        'type':           'debuff',
        'scale_stat':     'wisdom',
        'scale_mult':     0.6,
        'base_value':     18,
        'duration':       3,
        'level_bonus':    0.07,
    },
    'radiant_strike': {
        'id':             'radiant_strike',
        'name':           '✨ Сияющий удар',
        'description':    'Надёжный повторяемый holy-удар.',
        'weapon_id':      'holy_rod',
        'branch':         'B',
        'unlock_mastery': 3,
        'max_level':      5,
        'mana_cost':      22,
        'cooldown':       3,
        'type':           'damage',
        'scale_stat':     'wisdom',
        'scale_mult':     1.9,
        'base_value':     140,
        'level_bonus':    0.10,
        'damage_school':  'holy',
    },
    'rod_consecration': {
        'id':             'rod_consecration',
        'name':           '🌟 Освящение',
        'description':    'Создаёт освящённое давление: накладывает holy DoT на цель.',
        'weapon_id':      'holy_rod',
        'branch':         'B',
        'unlock_mastery': 5,
        'max_level':      5,
        'mana_cost':      28,
        'cooldown':       4,
        'type':           'debuff',
        'scale_stat':     'wisdom',
        'scale_mult':     1.2,
        'base_value':     18,
        'level_bonus':    0.10,
        'effect':         ('burn', 1.0, 3),
    },
    'punish_the_wicked': {
        'id':             'punish_the_wicked',
        'name':           '⚖️ Кара нечестивых',
        'description':    'Карательный holy-удар, существенно сильнее по осуждённой цели.',
        'weapon_id':      'holy_rod',
        'branch':         'B',
        'unlock_mastery': 7,
        'max_level':      5,
        'mana_cost':      30,
        'cooldown':       4,
        'type':           'damage',
        'scale_stat':     'wisdom',
        'scale_mult':     2.2,
        'base_value':     170,
        'level_bonus':    0.12,
        'damage_school':  'holy',
    },
    'final_verdict': {
        'id':             'final_verdict',
        'name':           '☀️ Финальный вердикт',
        'description':    'Капстоун Judicator: тяжёлый commit-удар, особенно опасный по осуждённой цели.',
        'weapon_id':      'holy_rod',
        'branch':         'B',
        'unlock_mastery': 10,
        'max_level':      5,
        'mana_cost':      42,
        'cooldown':       6,
        'type':           'damage',
        'scale_stat':     'wisdom',
        'scale_mult':     2.6,
        'base_value':     205,
        'level_bonus':    0.13,
        'damage_school':  'holy',
    },
    # ════════════════════════════════════════
    # 📚 ТОМ
    # ════════════════════════════════════════
    'arcane_shield': {
        'id':             'arcane_shield',
        'name':           '🛡️ Чародейский щит',
        'description':    'Защитное зачарование: снижает входящий урон для себя или союзника на короткое время.',
        'weapon_id':      'tome',
        'branch':         'A',
        'unlock_mastery': 1,
        'max_level':      5,
        'mana_cost':      18,
        'cooldown':       3,
        'type':           'buff',
        'target_kind':    'ally',
        'scale_stat':     'wisdom',
        'scale_mult':     0.4,
        'base_value':     12,
        'duration':       2,
        'level_bonus':    0.07,
    },
    'weaken': {
        'id':             'weaken',
        'name':           '🕸️ Ослабление',
        'description':    'Ослабляет атакующий напор врага: его урон падает на несколько ходов.',
        'weapon_id':      'tome',
        'branch':         'A',
        'unlock_mastery': 3,
        'max_level':      5,
        'mana_cost':      20,
        'cooldown':       3,
        'type':           'debuff',
        'target_kind':    'enemy',
        'scale_stat':     'wisdom',
        'scale_mult':     0.5,
        'base_value':     16,
        'duration':       2,
        'level_bonus':    0.07,
    },
    'insight': {
        'id':             'insight',
        'name':           '🔮 Прозрение',
        'description':    'Восстанавливает немного маны выбранной цели или группе.',
        'weapon_id':      'tome',
        'branch':         'A',
        'unlock_mastery': 5,
        'max_level':      5,
        'mana_cost':      22,
        'cooldown':       4,
        'type':           'buff',
        'target_kind':    'party',
        'scale_stat':     'wisdom',
        'scale_mult':     0.9,
        'base_value':     8,
        'duration':       1,
        'level_bonus':    0.08,
    },
    'dispel_script': {
        'id':             'dispel_script',
        'name':           '📜 Скрипт рассеивания',
        'description':    'Снимает поддерживаемый набор эффектов: очищает союзников и срывает часть усилений врага.',
        'weapon_id':      'tome',
        'branch':         'A',
        'unlock_mastery': 7,
        'max_level':      5,
        'mana_cost':      24,
        'cooldown':       4,
        'type':           'buff',
        'target_kind':    'party',
        'scale_stat':     'wisdom',
        'scale_mult':     0.7,
        'base_value':     10,
        'duration':       1,
        'level_bonus':    0.07,
    },
    'grand_enchantment': {
        'id':             'grand_enchantment',
        'name':           '🌌 Великое зачарование',
        'description':    'Капстоун поддержки: даёт группе ману и короткое защитное окно.',
        'weapon_id':      'tome',
        'branch':         'A',
        'unlock_mastery': 10,
        'max_level':      5,
        'mana_cost':      34,
        'cooldown':       6,
        'type':           'buff',
        'target_kind':    'party',
        'scale_stat':     'wisdom',
        'scale_mult':     1.0,
        'base_value':     12,
        'duration':       2,
        'level_bonus':    0.09,
    },
    'hybrid_missile': {
        'id':             'hybrid_missile',
        'name':           '🪄 Гибридный снаряд',
        'description':    'Гибкий базовый выстрел исследователя с умеренным смешанным скейлингом.',
        'weapon_id':      'tome',
        'branch':         'B',
        'unlock_mastery': 1,
        'max_level':      5,
        'mana_cost':      16,
        'cooldown':       2,
        'type':           'damage',
        'target_kind':    'enemy',
        'scale_stat':     'intuition',
        'scale_mult':     1.0,
        'base_value':     122,
        'level_bonus':    0.10,
        'damage_school':  'magic',
    },
    'borrowed_flame': {
        'id':             'borrowed_flame',
        'name':           '🔥 Заимствованное пламя',
        'description':    'Магическая настройка: наносит урон и поджигает цель через существующий burn pipeline.',
        'weapon_id':      'tome',
        'branch':         'B',
        'unlock_mastery': 3,
        'max_level':      5,
        'mana_cost':      20,
        'cooldown':       3,
        'type':           'debuff',
        'target_kind':    'enemy',
        'scale_stat':     'intuition',
        'scale_mult':     1.1,
        'base_value':     16,
        'level_bonus':    0.09,
        'damage_school':  'magic',
    },
    'borrowed_grace': {
        'id':             'borrowed_grace',
        'name':           '✨ Заимствованная благодать',
        'description':    'Лёгкий holy-удар и короткое окно благословения для гибридных связок.',
        'weapon_id':      'tome',
        'branch':         'B',
        'unlock_mastery': 5,
        'max_level':      5,
        'mana_cost':      22,
        'cooldown':       4,
        'type':           'damage',
        'target_kind':    'enemy',
        'scale_stat':     'wisdom',
        'scale_mult':     1.3,
        'base_value':     128,
        'level_bonus':    0.10,
        'damage_school':  'holy',
    },
    'synthesis': {
        'id':             'synthesis',
        'name':           '🧬 Синтез',
        'description':    'Payoff-каст: заметно усиливается, если активны burn и/или holy-окно.',
        'weapon_id':      'tome',
        'branch':         'B',
        'unlock_mastery': 7,
        'max_level':      5,
        'mana_cost':      26,
        'cooldown':       4,
        'type':           'damage',
        'target_kind':    'enemy',
        'scale_stat':     'intuition',
        'scale_mult':     1.5,
        'base_value':     150,
        'level_bonus':    0.11,
        'damage_school':  'magic',
    },
    'forbidden_thesis': {
        'id':             'forbidden_thesis',
        'name':           '⛔ Запретный тезис',
        'description':    'Капстоун Researcher: сильнейший гибридный финишер, потребляет setup только после успешного попадания.',
        'weapon_id':      'tome',
        'branch':         'B',
        'unlock_mastery': 10,
        'max_level':      5,
        'mana_cost':      34,
        'cooldown':       6,
        'type':           'damage',
        'target_kind':    'enemy',
        'scale_stat':     'intuition',
        'scale_mult':     1.8,
        'base_value':     172,
        'level_bonus':    0.12,
        'damage_school':  'magic',
    },
}

# ════════════════════════════════════════
# ДЕРЕВЬЯ НАВЫКОВ ПО ОРУЖИЮ
# ════════════════════════════════════════

SKILL_TREES = {
    'base': {
        'base': ['power_strike'],
    },
    'sword_1h': {
        'A': ['sword_rush', 'defensive_stance', 'shield_bash', 'parry', 'counter'],
        'B': ['driving_slash', 'expose_guard', 'press_the_line', 'punishing_cut', 'vanguard_surge'],
    },
    'wooden_sword': {
        'A': ['sword_rush', 'defensive_stance', 'shield_bash', 'parry', 'counter'],
        'B': ['driving_slash', 'expose_guard', 'press_the_line', 'punishing_cut', 'vanguard_surge'],
    },
    'iron_sword': {
        'A': ['sword_rush', 'defensive_stance', 'shield_bash', 'parry', 'counter'],
        'B': ['driving_slash', 'expose_guard', 'press_the_line', 'punishing_cut', 'vanguard_surge'],
    },
    'dagger': {
        'A': ['envenom_blades', 'toxic_cut', 'crippling_venom', 'widows_kiss', 'rupture_toxins'],
        'B': ['smoke_bomb', 'feint_step', 'quick_slice', 'backstab', 'shadow_chain'],
    },
    'short_bow': {
        'A': ['hunters_mark', 'aimed_shot', 'steady_aim', 'piercing_arrow', 'deadeye'],
        'B': ['quick_shot', 'hamstring_arrow', 'reposition', 'volley_step', 'rain_of_barbs'],
    },
    'axe_2h': {
        'A': ['rage_call', 'savage_chop', 'blooded_resolve', 'frenzy_chain', 'last_roar'],
        'B': ['bleeding_cut', 'sunder_armor', 'brutal_overhead', 'reopen_wounds', 'ravage'],
    },
    'sword_2h': {
        'A': ['heavy_swing', 'armor_split', 'executioners_focus', 'cleave_through', 'executioners_stroke'],
        'B': ['battle_stance', 'twin_cut', 'riposte_step', 'flowing_combo', 'masters_sequence'],
    },
    'magic_staff': {
        'A': ['fireball', 'arcane_surge', 'flame_wave', 'arcane_lance', 'cataclysm'],
        'B': ['frost_bolt', 'ice_shackles', 'mana_shield', 'shatter', 'absolute_zero'],
    },
    'wand': {
        'A': ['arcane_bolt', 'spell_echo', 'quick_channel', 'overload', 'arcane_barrage'],
        'B': ['dueling_ward', 'hex_bolt', 'mana_feint', 'counterpulse', 'duel_arc'],
    },
    'holy_staff': {
        'A': ['heal', 'regeneration', 'cleanse', 'blessing', 'resurrection'],
        'B': ['smite', 'radiant_ward', 'judgment_mark', 'sanctified_burst', 'halo_of_dawn'],
    },
    'holy_rod': {
        'A': ['sacred_shield', 'mend_self', 'aura_of_resolve', 'aegis_strike', 'guardian_light'],
        'B': ['judgment', 'radiant_strike', 'rod_consecration', 'punish_the_wicked', 'final_verdict'],
    },
    'tome': {
        'A': ['arcane_shield', 'weaken', 'insight', 'dispel_script', 'grand_enchantment'],
        'B': ['hybrid_missile', 'borrowed_flame', 'borrowed_grace', 'synthesis', 'forbidden_thesis'],
    },
}

def get_skill(skill_id: str) -> dict:
    return SKILLS.get(skill_id)

def _resolve_tree_key(weapon_id: str, weapon_profile: str | None = None) -> str:
    """
    Приоритетно используем дерево по weapon_id.
    Если его нет — пытаемся взять профильное дерево (минимальный bridge для slice).
    """
    if weapon_id in SKILL_TREES:
        return weapon_id
    if weapon_profile and weapon_profile in SKILL_TREES:
        return weapon_profile
    return weapon_id

def get_weapon_tree(weapon_id: str, weapon_profile: str | None = None) -> dict:
    tree_key = _resolve_tree_key(weapon_id, weapon_profile)
    return SKILL_TREES.get(tree_key, {})

def get_available_skills(weapon_id: str, mastery_level: int, weapon_profile: str | None = None) -> list:
    """Возвращает список доступных скиллов для данного оружия и уровня владения."""
    tree   = get_weapon_tree(weapon_id, weapon_profile)
    result = []

    # Базовые скиллы всегда доступны
    for skill_id in SKILL_TREES.get('base', {}).get('base', []):
        result.append(get_skill(skill_id))

    # Скиллы оружия
    for branch, skill_ids in tree.items():
        for skill_id in skill_ids:
            skill = get_skill(skill_id)
            if skill and mastery_level >= skill['unlock_mastery']:
                result.append(skill)

    return [s for s in result if s]

print(f'✅ game/skills.py загружен!')
print(f'   Скиллов: {len(SKILLS)}')
print(f'   Деревьев оружия: {len(SKILL_TREES)}')
