# ============================================================
# skills.py — все скиллы и деревья навыков
# ============================================================

# Структура скилла:
# id, name, description, weapon_id, branch (A/B),
# unlock_mastery (уровень владения для открытия),
# max_level, mana_cost, cooldown (ходы),
# type: damage/heal/buff/debuff/control,
# scale_stat, scale_mult, base_value, level_bonus
# duration — для баффов: кол-во ходов (не зависит от base_value)

SKILLS = {

    # ════════════════════════════════════════
    # БАЗОВЫЕ СКИЛЛЫ — есть у ВСЕХ оружий
    # ════════════════════════════════════════

    'power_strike': {
        'id':             'power_strike',
        'name':           '💢 Мощный удар',
        'description':    'Наносит 150% урона оружием.',
        'weapon_id':      'base',
        'branch':         'base',
        'unlock_mastery': 0,
        'max_level':      5,
        'mana_cost':      15,
        'cooldown':       2,
        'type':           'damage',
        'scale_stat':     None,
        'scale_mult':     0,
        'base_value':     150,
        'level_bonus':    0.15,
    },
    'defensive_stance': {
        'id':             'defensive_stance',
        'name':           '🛡️ Защитная стойка',
        'description':    'Стойка передовой: сильно снижает входящий урон и помогает держать линию.',
        'weapon_id':      'sword_1h',
        'branch':         'A',
        'unlock_mastery': 2,
        'max_level':      5,
        'mana_cost':      10,
        'cooldown':       3,
        'type':           'buff',
        'scale_stat':     'vitality',
        'scale_mult':     0.5,
        'base_value':     40,
        'duration':       2,
        'level_bonus':    0.05,
    },

    # ════════════════════════════════════════
    # ⚔️ ЖЕЛЕЗНЫЙ МЕЧ / ДЕРЕВЯННЫЙ МЕЧ
    # ════════════════════════════════════════

    # Ветка A — Guardian
    'sword_rush': {
        'id':             'sword_rush',
        'name':           '⚡ Рывок',
        'description':    'Дисциплинированный рывок в атаку: наносит урон и открывает цель под давление.',
        'weapon_id':      'iron_sword',
        'branch':         'A',
        'unlock_mastery': 1,
        'max_level':      5,
        'mana_cost':      20,
        'cooldown':       4,
        'type':           'damage',
        'scale_stat':     'strength',
        'scale_mult':     1.5,
        'base_value':     110,
        'level_bonus':    0.12,
    },
    'shield_bash': {
        'id':             'shield_bash',
        'name':           '🛡️ Удар щитом',
        'description':    'Короткий контроль: наносит небольшой урон, сбивает баланс и ослабляет урон врага.',
        'weapon_id':      'iron_sword',
        'branch':         'A',
        'unlock_mastery': 4,
        'max_level':      5,
        'mana_cost':      16,
        'cooldown':       3,
        'type':           'debuff',
        'scale_stat':     'vitality',
        'scale_mult':     0.7,
        'base_value':     26,
        'duration':       2,
        'level_bonus':    0.08,
    },

    # Ветка B — Vanguard
    'driving_slash': {
        'id':             'driving_slash',
        'name':           '⚔️ Продавливающий удар',
        'description':    'Наступающий удар для начала давления.',
        'weapon_id':      'iron_sword',
        'branch':         'B',
        'unlock_mastery': 1,
        'max_level':      5,
        'mana_cost':      18,
        'cooldown':       3,
        'type':           'damage',
        'scale_stat':     'strength',
        'scale_mult':     1.4,
        'base_value':     120,
        'level_bonus':    0.11,
    },
    'expose_guard': {
        'id':             'expose_guard',
        'name':           '🎯 Вскрытие защиты',
        'description':    'Открывает брешь в защите цели, усиливая последующие удары по ней.',
        'weapon_id':      'iron_sword',
        'branch':         'B',
        'unlock_mastery': 3,
        'max_level':      5,
        'mana_cost':      16,
        'cooldown':       3,
        'type':           'debuff',
        'scale_stat':     'agility',
        'scale_mult':     0.7,
        'base_value':     24,
        'duration':       2,
        'level_bonus':    0.07,
    },
    'press_the_line': {
        'id':             'press_the_line',
        'name':           '📣 Дави строй',
        'description':    'Короткое окно наступления: временно усиливает твой прямой урон.',
        'weapon_id':      'iron_sword',
        'branch':         'B',
        'unlock_mastery': 5,
        'max_level':      5,
        'mana_cost':      20,
        'cooldown':       4,
        'type':           'buff',
        'scale_stat':     'strength',
        'scale_mult':     0.6,
        'base_value':     16,
        'duration':       2,
        'level_bonus':    0.08,
    },
    'punishing_cut': {
        'id':             'punishing_cut',
        'name':           '🩸 Карательный разрез',
        'description':    'Сильнее бьёт по уже вскрытой цели.',
        'weapon_id':      'iron_sword',
        'branch':         'B',
        'unlock_mastery': 7,
        'max_level':      5,
        'mana_cost':      24,
        'cooldown':       4,
        'type':           'damage',
        'scale_stat':     'strength',
        'scale_mult':     1.7,
        'base_value':     150,
        'level_bonus':    0.12,
    },
    'vanguard_surge': {
        'id':             'vanguard_surge',
        'name':           '🚩 Натиск авангарда',
        'description':    'Ключевой финишер ветки: максимально силён в окно вскрытой защиты и темпа.',
        'weapon_id':      'iron_sword',
        'branch':         'B',
        'unlock_mastery': 10,
        'max_level':      5,
        'mana_cost':      36,
        'cooldown':       6,
        'type':           'damage',
        'scale_stat':     'strength',
        'scale_mult':     2.1,
        'base_value':     190,
        'level_bonus':    0.14,
    },
    'parry': {
        'id':             'parry',
        'name':           '🔄 Парирование',
        'description':    'Отражает следующую атаку врага. Со щитом отражение сильнее, но щит не обязателен.',
        'weapon_id':      'iron_sword',
        'branch':         'A',
        'unlock_mastery': 1,
        'max_level':      5,
        'mana_cost':      20,
        'cooldown':       4,
        'type':           'buff',
        'scale_stat':     'vitality',
        'scale_mult':     0.35,
        'base_value':     1.0,
        'duration':       1,
        'level_bonus':    0.1,
    },
    'disarm': {
        'id':             'disarm',
        'name':           '🤺 Обезоруживание',
        'description':    'Снижает урон врага на 40% на 2 хода.',
        'weapon_id':      'iron_sword',
        'branch':         'B',
        'unlock_mastery': 3,
        'max_level':      5,
        'mana_cost':      20,
        'cooldown':       3,
        'type':           'debuff',
        'scale_stat':     'agility',
        'scale_mult':     0.8,
        'base_value':     40,
        'level_bonus':    0.08,
    },
    'counter': {
        'id':             'counter',
        'name':           '⚔️ Контратака',
        'description':    'Пассивно: при получении урона есть шанс на ответный удар, особенно надёжный в защитном размене.',
        'weapon_id':      'iron_sword',
        'branch':         'A',
        'unlock_mastery': 4,
        'max_level':      5,
        'mana_cost':      0,
        'cooldown':       0,
        'type':           'passive',
        'scale_stat':     'vitality',
        'scale_mult':     0.8,
        'base_value':     30,
        'level_bonus':    0.05,
    },
    'sword_ultimate_b': {
        'id':             'sword_ultimate_b',
        'name':           '🌟 Непробиваемый',
        'description':    'На 3 хода становишься неуязвимым. Получаешь 0 урона.',
        'weapon_id':      'iron_sword',
        'branch':         'B',
        'unlock_mastery': 10,
        'max_level':      5,
        'mana_cost':      60,
        'cooldown':       8,
        'type':           'buff',
        'scale_stat':     'vitality',
        'scale_mult':     0.5,
        'base_value':     3,
        'duration':       3,
        'level_bonus':    0.2,
    },

    # ════════════════════════════════════════
    # 🗡️ КИНЖАЛ
    # ════════════════════════════════════════

    # Ветка A — Яды
    'poison_blade': {
        'id':             'poison_blade',
        'name':           '☠️ Ядовитый клинок',
        'description':    'Отравляет врага. 25% урона в ход на 3 хода.',
        'weapon_id':      'dagger',
        'branch':         'A',
        'unlock_mastery': 1,
        'max_level':      5,
        'mana_cost':      15,
        'cooldown':       3,
        'type':           'debuff',
        'scale_stat':     'agility',
        'scale_mult':     0.8,
        'base_value':     25,
        'level_bonus':    0.15,
        'effect':         ('poison', 1.0, 3),
    },
    'envenom': {
        'id':             'envenom',
        'name':           '🐍 Змеиный яд',
        'description':    'Усиливает яд. Следующее отравление наносит двойной урон.',
        'weapon_id':      'dagger',
        'branch':         'A',
        'unlock_mastery': 3,
        'max_level':      5,
        'mana_cost':      20,
        'cooldown':       4,
        'type':           'buff',
        'scale_stat':     'agility',
        'scale_mult':     1.0,
        'base_value':     2.0,
        'duration':       2,
        'level_bonus':    0.1,
    },
    'venom_storm': {
        'id':             'venom_storm',
        'name':           '💀 Смертельный яд',
        'description':    'Накладывает стек из 3 ядов одновременно.',
        'weapon_id':      'dagger',
        'branch':         'A',
        'unlock_mastery': 6,
        'max_level':      5,
        'mana_cost':      35,
        'cooldown':       5,
        'type':           'debuff',
        'scale_stat':     'agility',
        'scale_mult':     1.2,
        'base_value':     20,
        'level_bonus':    0.12,
        'effect':         ('poison', 1.0, 3),
    },
    'dagger_ult_a': {
        'id':             'dagger_ult_a',
        'name':           '🕷️ Паучье гнездо',
        'description':    'Ультимативный яд. 60% урона в ход на 5 ходов. Нельзя снять.',
        'weapon_id':      'dagger',
        'branch':         'A',
        'unlock_mastery': 10,
        'max_level':      5,
        'mana_cost':      60,
        'cooldown':       8,
        'type':           'debuff',
        'scale_stat':     'agility',
        'scale_mult':     2.0,
        'base_value':     60,
        'level_bonus':    0.15,
        'effect':         ('poison', 1.0, 5),
    },
    'envenom_blades': {
        'id':             'envenom_blades',
        'name':           '🐍 Отравленные клинки',
        'description':    'Подготавливает усиленный яд: следующее успешное отравление будет сильнее.',
        'weapon_id':      'dagger',
        'branch':         'A',
        'unlock_mastery': 1,
        'max_level':      5,
        'mana_cost':      16,
        'cooldown':       3,
        'type':           'buff',
        'scale_stat':     'agility',
        'scale_mult':     0.6,
        'base_value':     1.0,
        'duration':       2,
        'level_bonus':    0.1,
    },
    'toxic_cut': {
        'id':             'toxic_cut',
        'name':           '☠️ Токсичный разрез',
        'description':    'Наносит прямой урон и гарантированно накладывает 1 стак яда.',
        'weapon_id':      'dagger',
        'branch':         'A',
        'unlock_mastery': 3,
        'max_level':      5,
        'mana_cost':      18,
        'cooldown':       2,
        'type':           'damage',
        'scale_stat':     'agility',
        'scale_mult':     1.4,
        'base_value':     115,
        'level_bonus':    0.1,
    },
    'crippling_venom': {
        'id':             'crippling_venom',
        'name':           '🧪 Калечащий яд',
        'description':    'Ослабляет темп врага: режет урон и накладывает замедление.',
        'weapon_id':      'dagger',
        'branch':         'A',
        'unlock_mastery': 5,
        'max_level':      5,
        'mana_cost':      20,
        'cooldown':       3,
        'type':           'debuff',
        'scale_stat':     'agility',
        'scale_mult':     0.9,
        'base_value':     22,
        'duration':       2,
        'level_bonus':    0.08,
    },
    'widows_kiss': {
        'id':             'widows_kiss',
        'name':           '🕷️ Поцелуй вдовы',
        'description':    'Payoff-удар: сильнее по отравленной, ослабленной или вскрытой цели.',
        'weapon_id':      'dagger',
        'branch':         'A',
        'unlock_mastery': 7,
        'max_level':      5,
        'mana_cost':      24,
        'cooldown':       4,
        'type':           'damage',
        'scale_stat':     'agility',
        'scale_mult':     1.7,
        'base_value':     145,
        'level_bonus':    0.12,
    },
    'rupture_toxins': {
        'id':             'rupture_toxins',
        'name':           '💥 Разрыв токсинов',
        'description':    'Финишер ветки Venom: усиливается от активных ядов и поглощает их.',
        'weapon_id':      'dagger',
        'branch':         'A',
        'unlock_mastery': 10,
        'max_level':      5,
        'mana_cost':      34,
        'cooldown':       6,
        'type':           'damage',
        'scale_stat':     'agility',
        'scale_mult':     2.0,
        'base_value':     170,
        'level_bonus':    0.14,
    },

    # Ветка B — Уклонение и крит
    'backstab': {
        'id':             'backstab',
        'name':           '🗡️ Удар в спину',
        'description':    'Сильный burst по открытой цели (замедление, контроль или сбитый баланс).',
        'weapon_id':      'dagger',
        'branch':         'B',
        'unlock_mastery': 7,
        'max_level':      5,
        'mana_cost':      20,
        'cooldown':       2,
        'type':           'damage',
        'scale_stat':     'agility',
        'scale_mult':     2.0,
        'base_value':     130,
        'level_bonus':    0.12,
    },
    'smoke_bomb': {
        'id':             'smoke_bomb',
        'name':           '💨 Дымовая завеса',
        'description':    'Короткое защитное окно уклонения: помогает пережить ответный ход.',
        'weapon_id':      'dagger',
        'branch':         'B',
        'unlock_mastery': 1,
        'max_level':      5,
        'mana_cost':      20,
        'cooldown':       4,
        'type':           'buff',
        'scale_stat':     'agility',
        'scale_mult':     0.5,
        'base_value':     35,
        'duration':       2,
        'level_bonus':    0.08,
    },
    'feint_step': {
        'id':             'feint_step',
        'name':           '👣 Ложный шаг',
        'description':    'Короткий setup-бафф для следующего темпового удара.',
        'weapon_id':      'dagger',
        'branch':         'B',
        'unlock_mastery': 3,
        'max_level':      5,
        'mana_cost':      14,
        'cooldown':       2,
        'type':           'buff',
        'scale_stat':     'agility',
        'scale_mult':     0.5,
        'base_value':     1.0,
        'duration':       1,
        'level_bonus':    0.08,
    },
    'quick_slice': {
        'id':             'quick_slice',
        'name':           '⚡ Быстрый срез',
        'description':    'Темповый удар с малым КД; после Ложного шага усиливается и замедляет цель.',
        'weapon_id':      'dagger',
        'branch':         'B',
        'unlock_mastery': 5,
        'max_level':      5,
        'mana_cost':      16,
        'cooldown':       2,
        'type':           'damage',
        'scale_stat':     'agility',
        'scale_mult':     1.3,
        'base_value':     105,
        'level_bonus':    0.1,
    },
    'death_dance': {
        'id':             'death_dance',
        'name':           '💃 Смертельный танец',
        'description':    'Атакует 3 раза за ход. Каждый удар слабее но может крит.',
        'weapon_id':      'dagger',
        'branch':         'B',
        'unlock_mastery': 6,
        'max_level':      5,
        'mana_cost':      35,
        'cooldown':       4,
        'type':           'damage',
        'scale_stat':     'agility',
        'scale_mult':     1.5,
        'base_value':     80,
        'level_bonus':    0.1,
        'hits':           3,
    },
    'dagger_ult_b': {
        'id':             'dagger_ult_b',
        'name':           '👻 Тень смерти',
        'description':    'Телепортируется за спину врага. Следующие 3 атаки — гарантированный крит.',
        'weapon_id':      'dagger',
        'branch':         'B',
        'unlock_mastery': 10,
        'max_level':      5,
        'mana_cost':      55,
        'cooldown':       7,
        'type':           'buff',
        'scale_stat':     'luck',
        'scale_mult':     1.0,
        'base_value':     3,
        'duration':       3,
        'level_bonus':    0.2,
    },
    'shadow_chain': {
        'id':             'shadow_chain',
        'name':           '🌑 Цепь теней',
        'description':    'Финиширующая серия: 2 удара базово, 3-й удар по открытой цели.',
        'weapon_id':      'dagger',
        'branch':         'B',
        'unlock_mastery': 10,
        'max_level':      5,
        'mana_cost':      30,
        'cooldown':       5,
        'type':           'damage',
        'scale_stat':     'agility',
        'scale_mult':     1.8,
        'base_value':     90,
        'level_bonus':    0.12,
        'hits':           2,
    },

    # ════════════════════════════════════════
    # 🏹 КОРОТКИЙ ЛУК
    # ════════════════════════════════════════

    # Ветка A — Sniper
    'aimed_shot': {
        'id':             'aimed_shot',
        'name':           '🎯 Прицельный выстрел',
        'description':    'Точный выстрел по одной цели. По отмеченной цели бьёт сильнее.',
        'weapon_id':      'short_bow',
        'branch':         'A',
        'unlock_mastery': 3,
        'max_level':      5,
        'mana_cost':      25,
        'cooldown':       3,
        'type':           'damage',
        'scale_stat':     'intuition',
        'scale_mult':     2.0,
        'base_value':     200,
        'level_bonus':    0.12,
        'piercing':       True,
    },
    'hunters_mark': {
        'id':             'hunters_mark',
        'name':           '🔍 Метка охотника',
        'description':    'Помечает цель: следующие прямые атаки наносят дополнительный урон.',
        'weapon_id':      'short_bow',
        'branch':         'A',
        'unlock_mastery': 1,
        'max_level':      5,
        'mana_cost':      20,
        'cooldown':       4,
        'type':           'debuff',
        'scale_stat':     'intuition',
        'scale_mult':     0.8,
        'base_value':     25,
        'level_bonus':    0.08,
    },
    'steady_aim': {
        'id':             'steady_aim',
        'name':           '🧭 Твёрдый прицел',
        'description':    'Подготовка снайпера: следующий прямой выстрел будет гарантированным критом.',
        'weapon_id':      'short_bow',
        'branch':         'A',
        'unlock_mastery': 5,
        'max_level':      5,
        'mana_cost':      18,
        'cooldown':       4,
        'type':           'buff',
        'scale_stat':     'intuition',
        'scale_mult':     0.4,
        'base_value':     1,
        'duration':       1,
        'level_bonus':    0.05,
    },
    'piercing_arrow': {
        'id':             'piercing_arrow',
        'name':           '🏹 Пробивающая стрела',
        'description':    'Сильный выстрел с частичным игнором защиты. Ещё сильнее по отмеченной цели.',
        'weapon_id':      'short_bow',
        'branch':         'A',
        'unlock_mastery': 7,
        'max_level':      5,
        'mana_cost':      30,
        'cooldown':       4,
        'type':           'damage',
        'scale_stat':     'intuition',
        'scale_mult':     2.2,
        'base_value':     220,
        'level_bonus':    0.12,
        'ignore_defense': 0.45,
    },
    'deadeye': {
        'id':             'deadeye',
        'name':           '💀 Мёртвый глаз',
        'description':    'Капстоун Sniper: тяжёлый прицельный выстрел, максимум силы по отмеченной цели.',
        'weapon_id':      'short_bow',
        'branch':         'A',
        'unlock_mastery': 10,
        'max_level':      5,
        'mana_cost':      44,
        'cooldown':       6,
        'type':           'damage',
        'scale_stat':     'intuition',
        'scale_mult':     2.7,
        'base_value':     290,
        'level_bonus':    0.14,
        'ignore_defense': 0.55,
    },
    'eagle_eye': {
        'id':             'eagle_eye',
        'name':           '🦅 Орлиный глаз',
        'description':    'Следующие 3 атаки — гарантированный крит.',
        'weapon_id':      'short_bow',
        'branch':         'A',
        'unlock_mastery': 6,
        'max_level':      5,
        'mana_cost':      35,
        'cooldown':       5,
        'type':           'buff',
        'scale_stat':     'intuition',
        'scale_mult':     1.0,
        'base_value':     3,
        'duration':       3,
        'level_bonus':    0.2,
    },
    'bow_ult_a': {
        'id':             'bow_ult_a',
        'name':           '☄️ Пронзающая стрела',
        'description':    'Стрела пронзает все защиты. Урон x4, игнорирует 100% защиты.',
        'weapon_id':      'short_bow',
        'branch':         'A',
        'unlock_mastery': 10,
        'max_level':      5,
        'mana_cost':      60,
        'cooldown':       7,
        'type':           'damage',
        'scale_stat':     'intuition',
        'scale_mult':     3.5,
        'base_value':     350,
        'level_bonus':    0.15,
        'ignore_defense': 1.0,
    },

    # Ветка B — Ranger
    'quick_shot': {
        'id':             'quick_shot',
        'name':           '⚡ Быстрый выстрел',
        'description':    'Быстрая дешёвая атака для постоянного давления.',
        'weapon_id':      'short_bow',
        'branch':         'B',
        'unlock_mastery': 1,
        'max_level':      5,
        'mana_cost':      10,
        'cooldown':       1,
        'type':           'damage',
        'scale_stat':     'agility',
        'scale_mult':     1.2,
        'base_value':     110,
        'level_bonus':    0.08,
    },
    'hamstring_arrow': {
        'id':             'hamstring_arrow',
        'name':           '🪢 Подрезающая стрела',
        'description':    'Наносит урон и замедляет цель для кайта.',
        'weapon_id':      'short_bow',
        'branch':         'B',
        'unlock_mastery': 3,
        'max_level':      5,
        'mana_cost':      16,
        'cooldown':       3,
        'type':           'damage',
        'scale_stat':     'agility',
        'scale_mult':     1.4,
        'base_value':     125,
        'level_bonus':    0.10,
    },
    'reposition': {
        'id':             'reposition',
        'name':           '↩️ Репозиция',
        'description':    'Тактический шаг назад: повышает уклонение на короткое окно.',
        'weapon_id':      'short_bow',
        'branch':         'B',
        'unlock_mastery': 5,
        'max_level':      5,
        'mana_cost':      18,
        'cooldown':       4,
        'type':           'buff',
        'scale_stat':     'agility',
        'scale_mult':     0.7,
        'base_value':     45,
        'duration':       2,
        'level_bonus':    0.08,
    },
    'volley_step': {
        'id':             'volley_step',
        'name':           '🏃‍➡️ Шаг залпа',
        'description':    'Мобильная серия из 2 попаданий. Наносит больше урона по замедленной цели.',
        'weapon_id':      'short_bow',
        'branch':         'B',
        'unlock_mastery': 7,
        'max_level':      5,
        'mana_cost':      24,
        'cooldown':       4,
        'type':           'damage',
        'scale_stat':     'agility',
        'scale_mult':     1.7,
        'base_value':     70,
        'level_bonus':    0.11,
        'hits':           2,
    },
    'rain_of_barbs': {
        'id':             'rain_of_barbs',
        'name':           '🌵 Ливень шипов',
        'description':    'Капстоун Ranger: шквал стрел для темпа. Сильнее по замедленной цели.',
        'weapon_id':      'short_bow',
        'branch':         'B',
        'unlock_mastery': 10,
        'max_level':      5,
        'mana_cost':      34,
        'cooldown':       6,
        'type':           'damage',
        'scale_stat':     'agility',
        'scale_mult':     2.0,
        'base_value':     75,
        'level_bonus':    0.11,
        'hits':           3,
    },
    'retreat': {
        'id':             'retreat',
        'name':           '🏃 Отступление',
        'description':    'Отпрыгивает назад. +60% уклонения на 1 ход, атакует издали.',
        'weapon_id':      'short_bow',
        'branch':         'B',
        'unlock_mastery': 1,
        'max_level':      5,
        'mana_cost':      15,
        'cooldown':       3,
        'type':           'buff',
        'scale_stat':     'agility',
        'scale_mult':     0.8,
        'base_value':     60,
        'duration':       1,
        'level_bonus':    0.08,
    },
    'arrow_rain': {
        'id':             'arrow_rain',
        'name':           '🌧️ Дождь стрел',
        'description':    'Выпускает 5 стрел. Каждая наносит 40% урона.',
        'weapon_id':      'short_bow',
        'branch':         'B',
        'unlock_mastery': 3,
        'max_level':      5,
        'mana_cost':      30,
        'cooldown':       4,
        'type':           'damage',
        'scale_stat':     'intuition',
        'scale_mult':     1.5,
        'base_value':     40,
        'level_bonus':    0.1,
        'hits':           5,
    },
    'kite': {
        'id':             'kite',
        'name':           '🎪 Заманивание',
        'description':    'Замедляет врага. Он пропускает следующий ход.',
        'weapon_id':      'short_bow',
        'branch':         'B',
        'unlock_mastery': 6,
        'max_level':      5,
        'mana_cost':      25,
        'cooldown':       5,
        'type':           'control',
        'scale_stat':     'agility',
        'scale_mult':     0.5,
        'base_value':     1,
        'level_bonus':    0.2,
    },
    'bow_ult_b': {
        'id':             'bow_ult_b',
        'name':           '🌪️ Торнадо стрел',
        'description':    'Создаёт вихрь стрел. 8 ударов по 35% урона, шанс оглушения.',
        'weapon_id':      'short_bow',
        'branch':         'B',
        'unlock_mastery': 10,
        'max_level':      5,
        'mana_cost':      65,
        'cooldown':       8,
        'type':           'damage',
        'scale_stat':     'intuition',
        'scale_mult':     2.0,
        'base_value':     35,
        'level_bonus':    0.1,
        'hits':           8,
        'effect':         ('stun', 0.3, 1),
    },

    # ════════════════════════════════════════
    # 🔮 МАГИЧЕСКИЙ ПОСОХ
    # ════════════════════════════════════════

    # Ветка A — Огонь
    'fireball': {
        'id':             'fireball',
        'name':           '🔥 Огненный шар',
        'description':    'Запускает огненный шар. Может поджечь цель.',
        'weapon_id':      'magic_staff',
        'branch':         'A',
        'unlock_mastery': 1,
        'max_level':      5,
        'mana_cost':      20,
        'cooldown':       2,
        'type':           'damage',
        'scale_stat':     'intuition',
        'scale_mult':     2.0,
        'base_value':     140,
        'level_bonus':    0.15,
        'effect':         ('burn', 0.30, 2),
    },
    'burning_ground': {
        'id':             'burning_ground',
        'name':           '🌋 Горящая земля',
        'description':    'Поджигает землю под врагом. 25% урона в ход на 3 хода.',
        'weapon_id':      'magic_staff',
        'branch':         'A',
        'unlock_mastery': 3,
        'max_level':      5,
        'mana_cost':      25,
        'cooldown':       4,
        'type':           'debuff',
        'scale_stat':     'intuition',
        'scale_mult':     1.5,
        'base_value':     25,
        'level_bonus':    0.15,
        'effect':         ('burn', 1.0, 3),
    },
    'fire_shield': {
        'id':             'fire_shield',
        'name':           '🔆 Огненный щит',
        'description':    'Окружает огнём. Атакующий получает 30% твоего урона в ответ.',
        'weapon_id':      'magic_staff',
        'branch':         'A',
        'unlock_mastery': 6,
        'max_level':      5,
        'mana_cost':      30,
        'cooldown':       4,
        'type':           'buff',
        'scale_stat':     'intuition',
        'scale_mult':     1.2,
        'base_value':     30,
        'duration':       3,
        'level_bonus':    0.15,
    },
    'meteor': {
        'id':             'meteor',
        'name':           '☄️ Метеор',
        'description':    'Призывает метеор. Огромный урон + поджигает + оглушает.',
        'weapon_id':      'magic_staff',
        'branch':         'A',
        'unlock_mastery': 10,
        'max_level':      5,
        'mana_cost':      70,
        'cooldown':       7,
        'type':           'damage',
        'scale_stat':     'intuition',
        'scale_mult':     4.0,
        'base_value':     320,
        'level_bonus':    0.15,
        'effect':         ('stun', 0.5, 2),
    },

    # Ветка B — Лёд
    'ice_lance': {
        'id':             'ice_lance',
        'name':           '❄️ Ледяное копьё',
        'description':    'Пронзает врага льдом. Замедляет на 1 ход.',
        'weapon_id':      'magic_staff',
        'branch':         'B',
        'unlock_mastery': 1,
        'max_level':      5,
        'mana_cost':      20,
        'cooldown':       2,
        'type':           'damage',
        'scale_stat':     'intuition',
        'scale_mult':     1.8,
        'base_value':     130,
        'level_bonus':    0.12,
        'effect':         ('slow', 0.5, 1),
    },
    'ice_chains': {
        'id':             'ice_chains',
        'name':           '⛓️ Ледяные цепи',
        'description':    'Сковывает врага льдом. Пропускает ход.',
        'weapon_id':      'magic_staff',
        'branch':         'B',
        'unlock_mastery': 3,
        'max_level':      5,
        'mana_cost':      30,
        'cooldown':       4,
        'type':           'control',
        'scale_stat':     'intuition',
        'scale_mult':     0.5,
        'base_value':     1,
        'level_bonus':    0.2,
        'effect':         ('freeze', 0.8, 3),
    },
    'blizzard': {
        'id':             'blizzard',
        'name':           '🌨️ Метель',
        'description':    'Вызывает метель. Снижает точность врага на 40% на 3 хода.',
        'weapon_id':      'magic_staff',
        'branch':         'B',
        'unlock_mastery': 6,
        'max_level':      5,
        'mana_cost':      35,
        'cooldown':       5,
        'type':           'debuff',
        'scale_stat':     'intuition',
        'scale_mult':     1.0,
        'base_value':     40,
        'level_bonus':    0.08,
    },
    'absolute_zero': {
        'id':             'absolute_zero',
        'name':           '🧊 Абсолютный ноль',
        'description':    'Замораживает врага полностью на 4 хода.',
        'weapon_id':      'magic_staff',
        'branch':         'B',
        'unlock_mastery': 10,
        'max_level':      5,
        'mana_cost':      75,
        'cooldown':       8,
        'type':           'control',
        'scale_stat':     'intuition',
        'scale_mult':     3.0,
        'base_value':     3,
        'level_bonus':    0.2,
        'effect':         ('freeze', 1.0, 4),
    },

    # ════════════════════════════════════════
    # ✨ СВЯТОЙ ПОСОХ
    # ════════════════════════════════════════

    # Ветка A — Свет
    'holy_bolt': {
        'id':             'holy_bolt',
        'name':           '✨ Световой заряд',
        'description':    'Заряд света. Особенно эффективен против нежити.',
        'weapon_id':      'holy_staff',
        'branch':         'A',
        'unlock_mastery': 1,
        'max_level':      5,
        'mana_cost':      18,
        'cooldown':       2,
        'type':           'damage',
        'scale_stat':     'wisdom',
        'scale_mult':     2.0,
        'base_value':     130,
        'level_bonus':    0.15,
    },
    'smite': {
        'id':             'smite',
        'name':           '⚡ Кара небес',
        'description':    'Призывает молнию света. Оглушает на 1 ход.',
        'weapon_id':      'holy_staff',
        'branch':         'A',
        'unlock_mastery': 3,
        'max_level':      5,
        'mana_cost':      28,
        'cooldown':       3,
        'type':           'damage',
        'scale_stat':     'wisdom',
        'scale_mult':     2.5,
        'base_value':     170,
        'level_bonus':    0.12,
        'effect':         ('stun', 0.35, 1),
    },
    'consecration': {
        'id':             'consecration',
        'name':           '🌟 Освящение',
        'description':    'Освящает землю. 20% урона светом в ход врагу на 3 хода.',
        'weapon_id':      'holy_staff',
        'branch':         'A',
        'unlock_mastery': 6,
        'max_level':      5,
        'mana_cost':      35,
        'cooldown':       5,
        'type':           'debuff',
        'scale_stat':     'wisdom',
        'scale_mult':     1.5,
        'base_value':     20,
        'level_bonus':    0.15,
        'effect':         ('burn', 1.0, 3),
    },
    'divine_wrath': {
        'id':             'divine_wrath',
        'name':           '☀️ Божественный гнев',
        'description':    'Ультимативный удар светом. Огромный урон, лечит тебя на 50% нанесённого.',
        'weapon_id':      'holy_staff',
        'branch':         'A',
        'unlock_mastery': 10,
        'max_level':      5,
        'mana_cost':      70,
        'cooldown':       7,
        'type':           'damage',
        'scale_stat':     'wisdom',
        'scale_mult':     4.0,
        'base_value':     300,
        'level_bonus':    0.15,
        'lifesteal':      0.5,
    },

    # Ветка B — Исцеление
    'heal': {
        'id':             'heal',
        'name':           '💚 Исцеление',
        'description':    'Восстанавливает HP. Сила лечения растёт с Мудростью.',
        'weapon_id':      'holy_staff',
        'branch':         'B',
        'unlock_mastery': 1,
        'max_level':      5,
        'mana_cost':      20,
        'cooldown':       2,
        'type':           'heal',
        'scale_stat':     'wisdom',
        'scale_mult':     3.0,
        'base_value':     40,
        'level_bonus':    0.20,
    },
    'blessing': {
        'id':             'blessing',
        'name':           '🙏 Благословение',
        'description':    'Повышает все статы на 20% на 3 хода.',
        'weapon_id':      'holy_staff',
        'branch':         'B',
        'unlock_mastery': 3,
        'max_level':      5,
        'mana_cost':      30,
        'cooldown':       5,
        'type':           'buff',
        'scale_stat':     'wisdom',
        'scale_mult':     0.5,
        'base_value':     20,
        'duration':       3,
        'level_bonus':    0.08,
    },
    'regeneration': {
        'id':             'regeneration',
        'name':           '♻️ Регенерация',
        'description':    'Накладывает мощный реген на 4 хода.',
        'weapon_id':      'holy_staff',
        'branch':         'B',
        'unlock_mastery': 6,
        'max_level':      5,
        'mana_cost':      35,
        'cooldown':       5,
        'type':           'buff',
        'scale_stat':     'wisdom',
        'scale_mult':     2.0,
        'base_value':     25,
        'duration':       4,
        'level_bonus':    0.15,
    },
    'resurrection': {
        'id':             'resurrection',
        'name':           '💫 Воскрешение',
        'description':    'Если умрёшь в следующие 5 ходов — воскреснешь с 50% HP.',
        'weapon_id':      'holy_staff',
        'branch':         'B',
        'unlock_mastery': 10,
        'max_level':      5,
        'mana_cost':      80,
        'cooldown':       10,
        'type':           'buff',
        'scale_stat':     'wisdom',
        'scale_mult':     1.0,
        'base_value':     50,
        'duration':       5,
        'level_bonus':    0.1,
    },
}

# ════════════════════════════════════════
# ДЕРЕВЬЯ НАВЫКОВ ПО ОРУЖИЮ
# ════════════════════════════════════════

SKILL_TREES = {
    'base': {
        'base': ['power_strike'],
    },
    'sword_1h': {
        'A': ['sword_rush', 'defensive_stance', 'shield_bash', 'parry', 'counter'],
        'B': ['driving_slash', 'expose_guard', 'press_the_line', 'punishing_cut', 'vanguard_surge'],
    },
    'wooden_sword': {
        'A': ['sword_rush', 'defensive_stance', 'shield_bash', 'parry', 'counter'],
        'B': ['driving_slash', 'expose_guard', 'press_the_line', 'punishing_cut', 'vanguard_surge'],
    },
    'iron_sword': {
        'A': ['sword_rush', 'defensive_stance', 'shield_bash', 'parry', 'counter'],
        'B': ['driving_slash', 'expose_guard', 'press_the_line', 'punishing_cut', 'vanguard_surge'],
    },
    'dagger': {
        'A': ['envenom_blades', 'toxic_cut', 'crippling_venom', 'widows_kiss', 'rupture_toxins'],
        'B': ['smoke_bomb', 'feint_step', 'quick_slice', 'backstab', 'shadow_chain'],
    },
    'short_bow': {
        'A': ['hunters_mark', 'aimed_shot', 'steady_aim', 'piercing_arrow', 'deadeye'],
        'B': ['quick_shot', 'hamstring_arrow', 'reposition', 'volley_step', 'rain_of_barbs'],
    },
    'magic_staff': {
        'A': ['fireball', 'burning_ground', 'fire_shield', 'meteor'],
        'B': ['ice_lance', 'ice_chains', 'blizzard', 'absolute_zero'],
    },
    'holy_staff': {
        'A': ['holy_bolt', 'smite', 'consecration', 'divine_wrath'],
        'B': ['heal', 'blessing', 'regeneration', 'resurrection'],
    },
}

def get_skill(skill_id: str) -> dict:
    return SKILLS.get(skill_id)

def _resolve_tree_key(weapon_id: str, weapon_profile: str | None = None) -> str:
    """
    Приоритетно используем дерево по weapon_id.
    Если его нет — пытаемся взять профильное дерево (минимальный bridge для slice).
    """
    if weapon_id in SKILL_TREES:
        return weapon_id
    if weapon_profile and weapon_profile in SKILL_TREES:
        return weapon_profile
    return weapon_id

def get_weapon_tree(weapon_id: str, weapon_profile: str | None = None) -> dict:
    tree_key = _resolve_tree_key(weapon_id, weapon_profile)
    return SKILL_TREES.get(tree_key, {})

def get_available_skills(weapon_id: str, mastery_level: int, weapon_profile: str | None = None) -> list:
    """Возвращает список доступных скиллов для данного оружия и уровня владения."""
    tree   = get_weapon_tree(weapon_id, weapon_profile)
    result = []

    # Базовые скиллы всегда доступны
    for skill_id in SKILL_TREES.get('base', {}).get('base', []):
        result.append(get_skill(skill_id))

    # Скиллы оружия
    for branch, skill_ids in tree.items():
        for skill_id in skill_ids:
            skill = get_skill(skill_id)
            if skill and mastery_level >= skill['unlock_mastery']:
                result.append(skill)

    return [s for s in result if s]

print(f'✅ game/skills.py загружен!')
print(f'   Скиллов: {len(SKILLS)}')
print(f'   Деревьев оружия: {len(SKILL_TREES)}')
